Repository runtimeverification/haskell-backend, pull requests merged in 2019-05, with the labels that each got.

#624 repl: try bug fix
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
Labels: bug, current iteration

#626 repl: check if graphviz is installed
  kore/src/Kore/Repl/Interpreter.hs
Labels: bug, current iteration

#625 Added basic tests for the REPL Interpreter.
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
Labels: current iteration

#631 REPL / Aliases with no arguments
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration, feature

#639 Repl: alias with arguments
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Parser.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration, feature

#654 exists x. y=x simplification
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Unification/Substitution.hs
  kore/test/Test/Kore/Step/Simplification/Exists.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  kore/test/Test/Kore/Unification/Substitution.hs
Labels: bug, current iteration
