Repository runtimeverification/haskell-backend, pull requests merged in 2019-03, with the labels that each got.

#481 Separate generic axiom simplification code from function simplification
  src/main/haskell/kore/src/Kore/Builtin.hs
  src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
  src/main/haskell/kore/src/Kore/Builtin/KEqual.hs
  src/main/haskell/kore/src/Kore/Builtin/List.hs
  src/main/haskell/kore/src/Kore/Builtin/Map.hs
  src/main/haskell/kore/src/Kore/Builtin/Set.hs
  src/main/haskell/kore/src/Kore/Exec.hs
  src/main/haskell/kore/src/Kore/OnePath/Step.hs
  src/main/haskell/kore/src/Kore/OnePath/Verification.hs
  src/main/haskell/kore/src/Kore/Step/Axiom/Data.hs
  src/main/haskell/kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  src/main/haskell/kore/src/Kore/Step/Axiom/Identifier.hs
  src/main/haskell/kore/src/Kore/Step/Axiom/Matcher.hs
  src/main/haskell/kore/src/Kore/Step/Axiom/Registry.hs
  src/main/haskell/kore/src/Kore/Step/Axiom/UserDefined.hs
  src/main/haskell/kore/src/Kore/Step/BaseStep.hs
  src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
  src/main/haskell/kore/src/Kore/Step/Merging/ExpandedPattern.hs
  src/main/haskell/kore/src/Kore/Step/Merging/OrOfExpandedPattern.hs
  src/main/haskell/kore/src/Kore/Step/Search.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/And.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/AndPredicates.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs-boot
  src/main/haskell/kore/src/Kore/Step/Simplification/Application.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs-boot
  src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/Exists.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/ExpandedPattern.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/In.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/Pattern.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/PredicateSubstitution.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/Simplifier.hs
  src/main/haskell/kore/src/Kore/Step/Step.hs
  src/main/haskell/kore/src/Kore/Step/Substitution.hs
  src/main/haskell/kore/src/Kore/Step/Substitution.hs-boot
  src/main/haskell/kore/src/Kore/Unification/Procedure.hs
  src/main/haskell/kore/src/Kore/Unification/UnifierImpl.hs
  src/main/haskell/kore/test/Test/Kore/Attribute/Overload.hs
  src/main/haskell/kore/test/Test/Kore/Builtin/Builtin.hs
  src/main/haskell/kore/test/Test/Kore/Comparators.hs
  src/main/haskell/kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  src/main/haskell/kore/test/Test/Kore/Step/Axiom/Identifier.hs
  src/main/haskell/kore/test/Test/Kore/Step/Axiom/Matcher.hs
  src/main/haskell/kore/test/Test/Kore/Step/Axiom/Registry.hs
  src/main/haskell/kore/test/Test/Kore/Step/Axiom/UserDefined.hs
  src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
  src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
  src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
  src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
  src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
Labels: current iteration

#487 Hide successful tests by default
  src/main/haskell/kore/package.yaml
  src/main/haskell/kore/test/Driver.hs
  src/main/haskell/kore/test/Test.hs
Labels: current iteration

#486 Fix some leftover thing from the last ceil-as-or refactoring.
  src/main/haskell/kore/src/Kore/Step/MultiAnd.hs
  src/main/haskell/kore/src/Kore/Step/OrOfExpandedPattern.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/AndPredicates.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs
  src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
  src/main/haskell/kore/test/Test/Kore/Step/MultiAnd.hs
  src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
  src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
Labels: current iteration

#485 Kore.Step.Step.transitionRule: Do not silence unification failures
  src/main/haskell/kore/src/Kore/Step/BaseStep.hs
  src/main/haskell/kore/src/Kore/Step/Step.hs
  src/main/haskell/kore/test/Test/Kore/Step/Step.hs
Labels: current iteration

#498 k/working/*.golden: new syntax for `{_#Equals_}`
  Makefile
  include.mk
  scripts/kevm-integration.sh
  src/main/k/working/imp-concrete-heat-cool/tests/max-symbolic.search.final.output.golden
  src/main/k/working/imp-concrete-state/tests/max-symbolic.search.final.output.golden
  src/main/k/working/imp-map-strict/tests/max-symbolic.search.final.output.golden
  src/main/k/working/imp-map-unify-strict/tests/max-symbolic.search.final.output.golden
  src/main/k/working/imp-map-unify/tests/max-symbolic.search.final.output.golden
  src/main/k/working/imp-map/tests/max-symbolic.search.final.output.golden
  src/main/k/working/imp-monosorted/tests/max-symbolic.search.final.output.golden
  src/main/k/working/imp/tests/max-symbolic.search.final.output.golden
  src/main/k/working/search/tests/initial.final.output.golden
  src/main/k/working/search/tests/initial.one.output.golden
  src/main/k/working/search/tests/initial.plus.output.golden
  src/main/k/working/search/tests/initial.star.initial.output.golden
  src/main/k/working/search/tests/initial.star.output.golden
Labels: current iteration

#493 Fix design decision references.
  design-decisions/2018-10-24-And-Not-Exists-Simplification.md
Labels: current iteration

#495 Design doc for configuration splitting for equality axioms.
  docs/2019-03-06-Equality-Axiom-Configuration-Splitting.md
Labels: current iteration

#494 Equality axiom sorts
  kore/src/Kore/Step/AxiomPatterns.hs
Labels: current iteration

#496 Kore.Exec.prove: Return all failing results
  kore/src/Kore/Exec.hs
  kore/src/Kore/OnePath/Verification.hs
  kore/src/Kore/Step/Representation/OrOfExpandedPattern.hs
  kore/test/Test/Kore/OnePath/Verification.hs
Labels: current iteration

#501 Feature/repl step n
  include.mk
  kore/Makefile
  kore/app/exec/Main.hs
  kore/app/parser/Main.hs
  kore/app/repl/Main.hs
  kore/app/share/GlobalMain.hs
  kore/bench/exec/Main.hs
  kore/package.yaml
  kore/src/Kore/Exec.hs
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/OnePath/Verification.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Strategy.hs
  kore/test/Test/Kore.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Exec.hs
  kore/test/Test/Kore/OnePath/Step.hs
  kore/test/Test/Kore/OnePath/Verification.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
  kore/test/Test/Kore/Step/Axiom/Registry.hs
  kore/test/Test/Kore/Step/Axiom/UserDefined.hs
  kore/test/Test/Kore/Step/BaseStep.hs
  kore/test/Test/Kore/Step/Condition/Evaluator.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/Application.hs
  kore/test/Test/Kore/Step/Simplification/Ceil.hs
  kore/test/Test/Kore/Step/Simplification/Equals.hs
  kore/test/Test/Kore/Step/Simplification/Exists.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
  kore/test/Test/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Substitution.hs
  kore/test/Test/Kore/Unification/Unifier.hs
  src/main/k/working/imp/Makefile
  stack.yaml
Labels: current iteration

#484 Implement branching on predicates
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Simplification/Predicate.hs
  kore/src/Kore/Step/Simplification/PredicateSubstitution.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/ListT.hs
  kore/src/SMT.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/Equals.hs
  kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
  kore/test/Test/ListT.hs
Labels: current iteration

#499 Implement getExitCode
  kore/app/exec/Main.hs
  kore/src/Kore/AST/Valid.hs
  kore/src/Kore/Exec.hs
  kore/test/Test/Kore/Exec.hs
Labels: current iteration

#505 Update K Nightly version used for integration testing
  include.mk
  scripts/update-k-nightly-pr.sh
Labels: current iteration

#502 Feature/lts 13.12
  stack.yaml
Labels: current iteration

#507 Remove dead code
  kore/app/prover/Main.hs
  kore/package.yaml
  kore/src/Kore/AST/AstWithLocation.hs
  kore/src/Kore/AST/MLPatterns.hs
  kore/src/Kore/Building/AsAst.hs
  kore/src/Kore/Building/Implicit.hs
  kore/src/Kore/Building/Patterns.hs
  kore/src/Kore/Building/Sorts.hs
  kore/src/Kore/MetaML/Lift.hs
  kore/src/Kore/Variables/Sort.hs
  kore/src/Logic/Matching/Error.hs
  kore/src/Logic/Matching/Pattern.hs
  kore/src/Logic/Matching/Prover/Command.hs
  kore/src/Logic/Matching/Prover/Repl.hs
  kore/src/Logic/Matching/Prover/Repl/Class.hs
  kore/src/Logic/Matching/Rules/Dummy.hs
  kore/src/Logic/Matching/Rules/Kore.hs
  kore/src/Logic/Matching/Rules/Minimal.hs
  kore/src/Logic/Matching/Rules/Minimal/Syntax.hs
  kore/src/Logic/Matching/Signature.hs
  kore/src/Logic/Matching/Signature/Polymorphic.hs
  kore/src/Logic/Matching/Signature/Simple.hs
  kore/src/Logic/Matching/Syntax.hs
  kore/src/Logic/Proof/Hilbert.hs
  kore/test/Test/Kore/AST/MLPatterns.hs
  kore/test/Test/Kore/Variables/Sort.hs
  kore/test/Test/Logic/Matching/Rules/Kore/ProofAssistant.hs
  kore/test/Test/Logic/Matching/Rules/Minimal.hs
  kore/test/Test/Logic/Matching/Rules/OnePlusOne.hs
  kore/test/Test/Logic/Matching/Rules/OnePlusOne/Pattern.hs
  kore/test/Test/Logic/Matching/Rules/OnePlusOne/Rules.hs
Labels: current iteration

#497 Ceil integration
  include.mk
  kore/src/Kore/Debug.hs
  kore/src/Kore/OnePath/Verification.hs
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/BaseStep.hs
  src/main/k/working/imp/Makefile
  src/main/k/working/imp/prove/sum-div-spec.k
  src/main/python/debugger.py
Labels: current iteration

#510 Instances for ListT
  kore/src/Kore/Step/Representation/MultiOr.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/ListT.hs
  kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
Labels: current iteration

#508 Tests for branch pruning
  kore/src/Kore/Builtin/KEqual.hs
  kore/src/Kore/Step/Representation/MultiOr.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Simplification/PredicateSubstitution.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/TopBottom.hs
  kore/src/Kore/Unification/UnifierImpl.hs
  kore/test/Test/Kore/Step/Substitution.hs
  kore/test/Test/Kore/TopBottom.hs
  kore/test/Test/Kore/Unification/Unifier.hs
Labels: current iteration

#500 Refactoring Demo
  kore/src/Kore/ASTHelpers.hs
  kore/src/Kore/IndexedModule/Resolvers.hs
Labels: current iteration

#514 Show Axiom Location
  docs/attributes.md
  kore/src/Kore/Attribute/Axiom.hs
  kore/src/Kore/Attribute/Location.hs
  kore/src/Kore/Attribute/Source.hs
  kore/src/Kore/Attribute/SourceLocation.hs
  kore/src/Kore/Repl.hs
Labels: current iteration

#520 Extract original definition from IndexedModule
  kore/src/Kore/AST/MetaOrObject.hs
  kore/src/Kore/AST/Pure.hs
  kore/src/Kore/AST/PureToKore.hs
  kore/src/Kore/AST/Sentence.hs
  kore/src/Kore/IndexedModule/IndexedModule.hs
  kore/test/Test/Kore/AST/PureToKore.hs
Labels: current iteration

#511 Refactor rule application for branching
  kore/src/Kore/Attribute/Axiom.hs
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/Predicate/Predicate.hs
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/Axiom/UserDefined.hs
  kore/src/Kore/Step/AxiomPatterns.hs
  kore/src/Kore/Step/BaseStep.hs
  kore/src/Kore/Step/Pattern.hs
  kore/src/Kore/Step/Representation/ExpandedPattern.hs
  kore/src/Kore/Step/Representation/MultiAnd.hs
  kore/src/Kore/Step/Representation/PredicateSubstitution.hs
  kore/src/Kore/Step/Representation/Predicated.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Simplification/Equals.hs
  kore/src/Kore/Step/Simplification/Or.lhs
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/Unification/Substitution.hs
  kore/src/Kore/Unification/SubstitutionNormalization.hs
  kore/src/Kore/Unification/UnifierImpl.hs
  kore/test/Test/Kore/ASTVerifier/DefinitionVerifier.hs
  kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/PatternVerifier.hs
  kore/test/Test/Kore/Annotation/Valid.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Comparators.hs
  kore/test/Test/Kore/IndexedModule/Resolvers.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
  kore/test/Test/Kore/Step/AxiomPatterns.hs
  kore/test/Test/Kore/Step/BaseStep.hs
  kore/test/Test/Kore/Step/Simplification/Application.hs
  kore/test/Test/Kore/Step/Simplification/Equals.hs
  kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
  kore/test/Test/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Substitution.hs
  kore/test/Test/Tasty/HUnit/Extensions.hs
Labels: current iteration

#521 Reduce Pattern to an ordinary ADT
  kore/src/Kore/AST/Common.hs
  kore/src/Kore/AST/Lens.hs
  kore/src/Kore/AST/MLPatterns.hs
  kore/src/Kore/AST/Valid.hs
  kore/src/Kore/ASTUtils/AlphaCompare.hs
  kore/src/Kore/ASTUtils/SmartPatterns.hs
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Proof/Value.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/ASTUtils/AlphaCompare.hs
Labels: current iteration

#523 REPL Parser Tests
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration

#527 Move SMT handling to its own directory
  kore/app/exec/Main.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Condition/Evaluator.hs
  kore/src/Kore/Step/SMT/Evaluator.hs
  kore/src/Kore/Step/SMT/Lemma.hs
  kore/src/Kore/Step/SMT/Translate.hs
  kore/test/Test/Kore/Step/Condition/Evaluator.hs
Labels: current iteration

#528 show unevaluated or stuck leafs
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration

#531 Update K Nightly version used for integration testing
  include.mk
Labels: current iteration

#522 Incorrect free variables annotation
  kore/src/Kore/AST/PureToKore.hs
  kore/src/Kore/ASTVerifier/PatternVerifier.hs
  kore/src/Kore/Annotation/Valid.hs
  kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/PatternVerifier.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
Labels: bug, current iteration

#536 First step toward `IndexedModule` tests that are less sensitive to irrelevant changes
  kore/src/Kore/Error.hs
  kore/src/Kore/IndexedModule/Error.hs
  kore/src/Kore/IndexedModule/Resolvers.hs
  kore/test/Test/Kore/Error.hs
  kore/test/Test/Kore/IndexedModule/Error.hs
  kore/test/Test/Kore/IndexedModule/Resolvers.hs
Labels: current iteration

#534 Overlapping instance EqualWithExplanation String
  kore/test/Test/Kore/Comparators.hs
  kore/test/Test/Kore/Step/Representation/ExpandedPattern.hs
  kore/test/Test/Tasty/HUnit/Extensions.hs
Labels: current iteration

#538 Repl Omit Cells
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration, feature
