Repository runtimeverification/haskell-backend, pull requests merged in 2019-11, with the labels that each got.

#1188 Add LIST.update hook
  docs/hooks.md
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/List/List.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Builtin/List.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
Labels: feature

#1199 Unparse builtin collections associatively
  kore/src/Kore/Domain/Builtin.hs
Labels: feature

#1201 Merge rules in batches
  kore/app/exec/Main.hs
  kore/app/share/GlobalMain.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Step/Rule/Combine.hs
  kore/test/Test/Kore/Step/Rule/Combine.hs
Labels: automerge

#1194 Resolve simplifiable cycles
  kore/src/Branch.hs
  kore/src/Kore/Step/Simplification/Condition.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/Unification/Substitution.hs
  kore/src/Kore/Unification/SubstitutionNormalization.hs
  kore/src/Kore/Unification/SubstitutionSimplifier.hs
  kore/src/Kore/Unification/UnifierT.hs
  kore/src/ListT.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/Condition.hs
  kore/test/Test/Kore/Step/Simplification/Exists.hs
  kore/test/Test/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/test/Test/Kore/Unification/UnifierT.hs
  scripts/integration-kwasm.sh
  src/main/k/working/locals/Makefile
  src/main/k/working/locals/locals.k
  src/main/k/working/locals/proofs/locals-spec.k
  src/main/k/working/tiny/Makefile
Labels: feature

#1214 LTS Haskell 14.13
  stack.yaml
  stack.yaml.lock
Labels: automerge

#1216 Dockerfile: Install z3-4.6
  Dockerfile
Labels: automerge

#1213 Start cleaning up logging options
  kore/src/Kore/Logger.hs
  kore/src/Kore/Logger/Output.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge

#1222 Jenkinsfile: Do not fail because of rv-devops jobs
  Jenkinsfile
Labels: automerge, jenkins

#1228 Update dependencies
  deps/k_release
Labels: automerge

#1226 Added KORE_EXEC_OPTS environment variable
  kore/app/share/GlobalMain.hs
Labels: automerge

#1217 Introduction to the Haskell backend
  docs/introduction.md
Labels: automerge

#1235 assertFunctionLikeResults: Do not re-evaluate results
  kore/src/Kore/Step/Axiom/Evaluate.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Result.hs
  kore/src/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Axiom/Evaluate.hs
Labels: automerge

#1229 Attributes for klabel and symbolKywd
  kore/src/Kore/Attribute/Assoc.hs
  kore/src/Kore/Attribute/Axiom/Concrete.hs
  kore/src/Kore/Attribute/Axiom/Constructor.hs
  kore/src/Kore/Attribute/Axiom/Unit.hs
  kore/src/Kore/Attribute/Comm.hs
  kore/src/Kore/Attribute/Constructor.hs
  kore/src/Kore/Attribute/Function.hs
  kore/src/Kore/Attribute/Functional.hs
  kore/src/Kore/Attribute/Idem.hs
  kore/src/Kore/Attribute/Injective.hs
  kore/src/Kore/Attribute/Parser.hs
  kore/src/Kore/Attribute/Simplification.hs
  kore/src/Kore/Attribute/SmtLemma.hs
  kore/src/Kore/Attribute/Sort/HasDomainValues.hs
  kore/src/Kore/Attribute/Symbol.hs
  kore/src/Kore/Attribute/Symbol/Anywhere.hs
  kore/src/Kore/Attribute/Symbol/Klabel.hs
  kore/src/Kore/Attribute/Symbol/Memo.hs
  kore/src/Kore/Attribute/Symbol/SymbolKywd.hs
  kore/src/Kore/Attribute/Trusted.hs
  kore/test/Test/Kore/Attribute/Symbol.hs
  kore/test/Test/Kore/Attribute/Symbol/Klabel.hs
  kore/test/Test/Kore/Attribute/Symbol/SymbolKywd.hs
  kore/test/Test/Kore/Internal/Symbol.hs
Labels: automerge

#1236 Allow building with Cabal out-of-the-box
  .gitignore
  cabal.project
  kore/package.yaml
Labels: automerge

#1230 Test.Kore.Repl.Interpreter: Remove debug output
  kore/test/Test/Kore/Repl/Interpreter.hs
Labels: automerge, bug

#1240 Handle IOException when we can't find 'z3'
  kore/src/SMT.hs
Labels: automerge

#1238 Pattern verifiers for builtin symbols
  kore/app/share/GlobalMain.hs
  kore/bench/exec/Main.hs
  kore/src/Kore/ASTVerifier/PatternVerifier.hs
  kore/src/Kore/ASTVerifier/SentenceVerifier.hs
  kore/src/Kore/Builtin.hs
  kore/src/Kore/Builtin/Bool.hs
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Builtin/Int.hs
  kore/src/Kore/Builtin/InternalBytes.hs
  kore/src/Kore/Builtin/KEqual.hs
  kore/src/Kore/Builtin/Krypto.hs
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Builtin/String.hs
  kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/PatternVerifier.hs
Labels: automerge

#1248 WarnUnhookedSymbol
  kore/src/Kore/Logger/WarnUnhookedSymbol.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/Simplification/Simplify.hs
Labels: automerge

#1241 DomainValue for Bytes
  kore/package.yaml
  kore/src/Kore/Builtin/Bool.hs
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Builtin/Encoding.hs
  kore/src/Kore/Builtin/External.hs
  kore/src/Kore/Builtin/Int.hs
  kore/src/Kore/Builtin/InternalBytes.hs
  kore/src/Kore/Builtin/InternalBytes/InternalBytes.hs
  kore/src/Kore/Builtin/String.hs
  kore/src/Kore/Internal/InternalBytes.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Builtin/InternalBytes.hs
Labels: automerge

#1257 Fix format of simplication-with-remainders warning
  kore/src/Kore/Logger/WarnSimplificationWithRemainder.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
Labels: automerge

#1242 Recognize Endianness and Signedness constructors
  kore/src/Kore/Attribute/Pattern/NonSimplifiable.hs
  kore/src/Kore/Attribute/Symbol/SymbolKywd.hs
  kore/src/Kore/Builtin.hs
  kore/src/Kore/Builtin/Endianness.hs
  kore/src/Kore/Builtin/Endianness/Endianness.hs
  kore/src/Kore/Builtin/External.hs
  kore/src/Kore/Builtin/Signedness.hs
  kore/src/Kore/Builtin/Signedness/Signedness.hs
  kore/src/Kore/Internal/Symbol.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/SMT/Translate.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/test/Test/ConsistentKore.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Builtin/Endianness.hs
  kore/test/Test/Kore/Builtin/Signedness.hs
Labels: automerge

#1232 ReachabilityRule as Claim
  kore/app/exec/Main.hs
  kore/app/repl/Main.hs
  kore/package.yaml
  kore/src/Kore/Exec.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Step/Rule/Expand.hs
  kore/src/Kore/Step/Rule/Simplify.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  kore/test/Test/Kore/Strategies/Reachability/Verification.hs
Labels: feature

#1244 Hook BYTES.int2bytes
  docs/hooks.md
  kore/src/Kore/Builtin/InternalBytes.hs
  kore/src/Kore/Builtin/InternalBytes/InternalBytes.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Builtin/InternalBytes.hs
Labels: automerge

#1273 Repl: can only try to apply claims of the same type
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Strategies/Verification.hs
Labels: bug

#1239 Update unparse instance for rules
  kore/src/Kore/Step/Rule.hs
  kore/test/Test/Kore/Step/Rule.hs
  src/main/k/working/imp/merge/1.merge-golden
  src/main/k/working/imp/merge/2.merge-golden
Labels: automerge

#1279 Hook: BYTES.bytes2int
  docs/hooks.md
  kore/src/Kore/Builtin/InternalBytes.hs
  kore/src/Kore/Builtin/InternalBytes/InternalBytes.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Builtin/InternalBytes.hs
Labels: automerge

#1284 Decode function axiom ensures clause
  kore/src/Kore/Step/Rule.hs
Labels: bug

#1280 Generalize DomainValueVerifier and ApplicationVerifier
  kore/src/Kore/ASTVerifier/PatternVerifier.hs
  kore/src/Kore/Builtin.hs
  kore/src/Kore/Builtin/Bool.hs
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Builtin/Endianness.hs
  kore/src/Kore/Builtin/Int.hs
  kore/src/Kore/Builtin/InternalBytes.hs
  kore/src/Kore/Builtin/KEqual.hs
  kore/src/Kore/Builtin/Krypto.hs
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Builtin/Signedness.hs
  kore/src/Kore/Builtin/String.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
Labels: automerge

#1288 Replace concrete check with toKey check
  kore/src/Kore/Attribute/Pattern/NonSimplifiable.hs
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Proof/Value.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Proof/Value.hs
Labels: automerge, bug

#1292 Update dependencies
  Makefile
  deps/k_release
  include.mk
  scripts/update-k-nightly-pr.sh
  scripts/update-k-nightly.sh
Labels: automerge

#1287 Hook: MAP.lookupOrDefault
  docs/hooks.md
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Map/Map.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/SMT.hs
Labels: automerge, feature

#1286 BYTES.length: Not an error to have symbolic Bytes
  kore/src/Kore/Builtin/InternalBytes.hs
Labels: automerge, bug

#1298 Revert "Update dependencies"
  Makefile
  deps/k_release
  include.mk
  scripts/update-k-nightly-pr.sh
  scripts/update-k-nightly.sh
Labels: automerge

#1254 Overloaded constructors and domain values
  kore/src/Kore/Step/Simplification/Overloading.hs
  src/main/k/working/tests/overloads/domain-values/Makefile
  src/main/k/working/tests/overloads/domain-values/domain-values.k
  src/main/k/working/tests/overloads/domain-values/prove/domain-values-spec.k
Labels: bug
