Repository runtimeverification/haskell-backend, pull requests merged in 2019-07, with the labels that each got.

#801 Fix AC unification loop
  kore/src/Kore/Builtin/AssociativeCommutative.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Set.hs
Labels: bug

#797 Print timing info to the log
  kore/app/exec/Main.hs
  kore/app/parser/Main.hs
  kore/app/repl/Main.hs
  kore/app/share/GlobalMain.hs
Labels: estimated size: S

#800 Evaluating functions with undefined arguments
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Remainder.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
Labels: estimated size: M

#789 Evaluate functions by matching instead of unification
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Result.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Unification/Unify.hs
  kore/test/Test/Kore/Builtin.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/IndexedModule/MockMetadataTools.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
  kore/test/Test/Kore/Step/Condition/Evaluator.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/Ceil.hs
  kore/test/Test/Kore/Step/Simplification/Equals.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  src/main/k/working/tests/collections/list-requires/list-requires.k
Labels: estimated size: L, feature
