Repository runtimeverification/haskell-backend, pull requests merged in 2019-06, with the labels that each got.

#684 Existential quantification for new step variables
  kore/src/Kore/ModelChecker/Simplification.hs
  kore/src/Kore/ModelChecker/Step.hs
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/Simplification/Pattern.hs
  kore/src/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  kore/test/Test/Kore/Step/Simplification/Pattern.hs
  kore/test/Test/Kore/Step/Step.hs
  src/main/k/working/tests/fresh-vars/Makefile
  src/main/k/working/tests/fresh-vars/fresh-vars.k
  src/main/k/working/tests/fresh-vars/tests/1.fresh-vars
  src/main/k/working/tests/fresh-vars/tests/1.output.golden
Labels: bug, current iteration

#745 Remove config environment from ReplState
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/State.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
Labels: current iteration

#759 repl: commands which write to files crash repl when directory does not exist
  kore/package.yaml
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
Labels: bug
