Repository runtimeverification/haskell-backend, pull requests merged in 2019-09, with the labels that each got.

#926 Fix instance Hashable Id
  kore/src/Kore/Syntax/Id.hs
  kore/test/Test/Kore/Syntax/Id.hs
Labels: bug

#956 Track pattern origins
  kore/src/Kore/Attribute/Pattern.hs
  kore/src/Kore/Attribute/Pattern/Created.hs
  kore/src/Kore/Debug.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/test/Test/Kore/Comparators.hs
Labels: size: M

#977 Fix a bug in the condition evaluator
  kore/src/Kore/Step/Condition/Evaluator.hs
  scripts/kevm-integration.sh
  src/main/k/evm-semantics/.gitignore
  src/main/k/evm-semantics/Makefile
  src/main/k/evm-semantics/sum-to-n/Makefile
  src/main/k/evm-semantics/sum-to-n/sum-to-n-spec.k
  src/main/k/evm-semantics/sum-to-n/sum-to-n-spec.kprove.golden
Labels: bug

#955 Refactor Kore.Strategies
  kore/src/Kore/Exec.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/OnePath/Actions.hs
  kore/src/Kore/Strategies/ProofState.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  kore/test/Test/Kore/Strategies/OnePath/Verification.hs
Labels: estimate: over, size: M

#986 REPL: logging scopes in log command
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: size: S

#995 log mappings between internal variables and SMT variables
  kore/src/Kore/Logger.hs
  kore/src/Kore/Step/SMT/Evaluator.hs
Labels: feature

#992 Jenkinsfile: Test stages in sequence
  Jenkinsfile
Labels: jenkins

#1009 scripts/ktest.sh: Cannot run different frontend processes in parallel
  scripts/ktest.sh
Labels: jenkins
