Repository runtimeverification/haskell-backend, pull requests merged in 2019-10, with the labels that each got.

#1042 Jenkinsfile: Run integration tests in parallel
  Jenkinsfile
Labels: jenkins

#1046 docs/glossary.md: Describe sort injections
  docs/glossary.md
Labels: question

#1053 runSMT: Stop solver gracefully upon error
  kore/src/SMT.hs
Labels: bug

#1092 Kore.Step.Step: Postpone checkSubstitutionCoverage
  kore/src/Kore/Step/Step.hs
Labels: bug

#1102 TermLike.simplifyInternal: Relax the pattern simplification check
  kore/src/Kore/Step/Simplification/TermLike.hs
Labels: bug

#1088 Jenkinsfile: Collect performance statistics
  Jenkinsfile
  scripts/integration-kevm.sh
  scripts/integration-kwasm.sh
Labels: jenkins

#1112 Run both kwasm tests
  scripts/integration-kwasm.sh
Labels: bug

#1144 Revert "Kore.Step.Simplification.SubstitutionSimplifier"
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Unification/Substitution.hs
  kore/src/Kore/Unification/SubstitutionNormalization.hs
  kore/src/Kore/Unification/UnifierImpl.hs
  kore/test/Test/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
Labels: bug

#1154 Only re-order variable-renaming substitutions
  kore/src/Kore/Unification/UnifierImpl.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
Labels: bug
