Repository runtimeverification/haskell-backend, pull requests merged in 2019-12, with the labels that each got.

#1301 Update dependencies
  Makefile
  deps/k_release
  include.mk
  scripts/update-k-nightly-pr.sh
  scripts/update-k-nightly.sh
Labels: automerge

#1307 Kore.IndexedModule.SortGraph
  kore/src/Kore/IndexedModule/MetadataTools.hs
  kore/src/Kore/IndexedModule/SortGraph.hs
  kore/test/Test/Kore/IndexedModule/MetadataTools.hs
  kore/test/Test/Kore/IndexedModule/SortGraph.hs
Labels: automerge

#1312 Configurable proof search order
  kore/app/exec/Main.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/test/Test/Kore/Strategies/Common.hs
Labels: automerge

#1293 Remove destination with configuration splitting
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Step/Simplification/Exists.hs
  kore/test/Test/Kore/Strategies/AllPath/Verification.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  kore/test/Test/Kore/Strategies/OnePath/Verification.hs
  kore/test/Test/Kore/Strategies/Reachability/Verification.hs
  src/main/k/working/all-path/00-basic/01-one-rule/provable/all-path-b-or-c-spec.k
  src/main/k/working/all-path/00-basic/03-concurrent-rules/provable/all-path-b-or-c-spec.k
  src/main/k/working/all-path/03-unification/set-select/notprovable/all-path-b-or-c-spec.k
  src/main/k/working/all-path/03-unification/set-select/provable/all-path-b-or-c-spec.k
  src/main/k/working/all-path/03-unification/set-select/provable/one-path-b-or-c-spec.k
Labels: feature

#1314 Fix smt prelude parsing
  kore/src/SMT/AST.hs
  kore/src/SMT/SimpleSMT.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/SMT/AST.hs
Labels: automerge

#1299 List unification with unit.
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Step/Rule/Simplify.hs
  kore/src/Kore/Step/Simplification/OrPattern.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/test/Test/Kore/Builtin/List.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  src/main/k/working/imp/merge/1.merge-golden
  src/main/k/working/imp/merge/2.merge-golden
  src/main/k/working/tests/collections/list-unify-assoc/Makefile
  src/main/k/working/tests/collections/list-unify-assoc/list-unify-assoc.k
  src/main/k/working/tests/collections/list-unify-assoc/proofs/push-spec.k
Labels: automerge

#1313 Update dependencies
  deps/k_release
Labels: automerge

#1330 LTS Haskell 14.16
  stack.yaml
  stack.yaml.lock
Labels: automerge

#1326 Update dependencies
  deps/k_release
Labels: automerge

#1323 Log equality axiom evaluation
  kore/src/Kore/Logger/DebugAppliedRule.hs
  kore/src/Kore/Logger/DebugAxiomEvaluation.hs
  kore/src/Kore/Logger/Output.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge

#1333 Evaluate concrete functions only on non-simplifiable arguments
  kore/src/Kore/Step/Axiom/Evaluate.hs
  kore/test/Test/Kore/Step/Axiom/Evaluate.hs
  src/main/k/working/tests/concrete/Makefile
  src/main/k/working/tests/concrete/concrete.k
  src/main/k/working/tests/concrete/tests/1.concrete
  src/main/k/working/tests/concrete/tests/1.output.golden
  src/main/k/working/tests/concrete/tests/2.concrete
  src/main/k/working/tests/concrete/tests/2.output.golden
Labels: automerge

#1331 Function evaluation logging
  kore/src/Kore/Logger/DebugAxiomEvaluation.hs
  kore/src/Kore/Step/Axiom/Evaluate.hs
  kore/src/Kore/Step/Function/Evaluator.hs
Labels: automerge

#1337 Log warning when hooks evaluate to bottom
  kore/src/Kore/Logger/WarnBottomHook.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
Labels: automerge

#1334 Memoize applications with non-simplifiable arguments
  kore/src/Kore/Step/Function/Evaluator.hs
Labels: automerge

#1332 Fix bug in sort injection unification
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/InjSimplifier.hs
  kore/src/Pair.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/InjSimplifier.hs
Labels: bug

#1338 SMT solver transcript
  kore/src/Kore/Logger/DebugSolver.hs
  kore/src/Kore/Logger/Output.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge

#1336 Refactored right and ensures to RHS
  kore/Makefile
  kore/src/Kore/Exec.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/ModelChecker/Bounded.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Step/EquationalStep.hs
  kore/src/Kore/Step/RewriteStep.hs
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Step/Rule/Combine.hs
  kore/src/Kore/Step/Rule/Expand.hs
  kore/src/Kore/Step/Rule/Simplify.hs
  kore/src/Kore/Step/Simplification/Rule.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Step.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/EquationalStep.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Step/Rule.hs
  kore/test/Test/Kore/Step/Rule/Combine.hs
  kore/test/Test/Kore/Step/Rule/Expand.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  kore/test/Test/Kore/Strategies/AllPath/Verification.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  kore/test/Test/Kore/Strategies/OnePath/Verification.hs
  kore/test/Test/Kore/Strategies/Reachability/Verification.hs
  src/main/k/working/imp/merge/1.merge-golden
  src/main/k/working/imp/merge/2.merge-golden
Labels: automerge

#1344 Fix smt solver log changes
  kore/src/Kore/Logger/Output.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
Labels: automerge

#1316 Simplify sort injections during matching
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/Simplification/InjSimplifier.hs
  kore/test/Test/Kore/Step/Simplification/InjSimplifier.hs
  src/main/k/working/matching-inj/Makefile
  src/main/k/working/matching-inj/a.output.golden
  src/main/k/working/matching-inj/a.run
  src/main/k/working/matching-inj/b.output.golden
  src/main/k/working/matching-inj/b.run
  src/main/k/working/matching-inj/run.k
Labels: automerge

#1343 Update dependencies
  deps/k_release
Labels: automerge

#1352 Fix map matching
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/Simplification/Rule.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
  src/main/k/working/tests/with-config/Makefile
  src/main/k/working/tests/with-config/prove/one-spec.k
  src/main/k/working/tests/with-config/prove/owise-spec.k
  src/main/k/working/tests/with-config/with-config.k
Labels: automerge

#1363 Normalize .Bytes in PatternVerifier
  kore/src/Kore/Builtin/InternalBytes.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Axiom/Matcher.hs
Labels: automerge

#1365 Break up Kore.Internal.TermLike
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
Labels: automerge

#1356 Dump proven claims to file
  kore/app/exec/Main.hs
  kore/app/share/GlobalMain.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/test/Test/Kore/Strategies/AllPath/Verification.hs
  kore/test/Test/Kore/Strategies/Common.hs
  kore/test/Test/Kore/Strategies/OnePath/Verification.hs
  kore/test/Test/Kore/Strategies/Reachability/Verification.hs
  src/main/k/working/imp/Makefile
  src/main/k/working/imp/save-proofs/sum-spec.k
  src/main/k/working/imp/save-proofs/sum-spec.save-proofs-golden
  src/main/k/working/include.mk
Labels: automerge

#1375 Jenkinsfile: switch to generic submodule updater
  Jenkinsfile
Labels: automerge

#1362 Update dependencies
  deps/k_release
Labels: automerge

#1370 Add registry of log entry types
  kore/src/Kore/Logger/DebugSolver.hs
  kore/src/Kore/Logger/Output.hs
  kore/src/Kore/Logger/Registry.hs
  kore/src/Kore/Logger/WarnBottomHook.hs
  kore/src/Kore/Logger/WarnFunctionWithoutEvaluators.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge
