Repository runtimeverification/haskell-backend, pull requests merged in 2019-04, with the labels that each got.

#545 removed outdated (and untested) K integration tests
  src/main/k/in-progress/imp-concrete-heat-cool/Makefile
  src/main/k/in-progress/imp-concrete-heat-cool/imp.k
  src/main/k/in-progress/imp-concrete-heat-cool/imp.kore
  src/main/k/in-progress/imp-concrete-heat-cool/tests/collatz.imp
  src/main/k/in-progress/imp-concrete-heat-cool/tests/primes.imp
  src/main/k/in-progress/imp-concrete-heat-cool/tests/sum.imp
  src/main/k/in-progress/imp-functional-state/imp.k
  src/main/k/in-progress/imp-functional-state/tests/sum.imp
  src/main/k/in-progress/imp-monosorted-strict/Makefile
  src/main/k/in-progress/imp-monosorted-strict/imp.k
  src/main/k/in-progress/imp-monosorted-strict/tests/collatz.imp
  src/main/k/in-progress/imp-monosorted-strict/tests/collatz.output.golden
  src/main/k/in-progress/imp-monosorted-strict/tests/primes.imp
  src/main/k/in-progress/imp-monosorted-strict/tests/primes.output.golden
  src/main/k/in-progress/imp-monosorted-strict/tests/sum.imp
  src/main/k/in-progress/imp-monosorted-strict/tests/sum.output.golden
  src/main/k/in-progress/imp-no-domains/Makefile
  src/main/k/in-progress/imp-no-domains/imp.k
  src/main/k/in-progress/imp-no-domains/tests/sum.imp
  src/main/k/in-progress/tests/collections/list/list-unify-any-elem/Makefile
  src/main/k/in-progress/tests/collections/list/list-unify-any-elem/list-unify-any-elem.k
  src/main/k/in-progress/tests/collections/list/list-unify-any-elem/tests/1.list-unify-any-elem
  src/main/k/in-progress/tests/collections/list/list-unify-any-elem/tests/1.output.golden
  src/main/k/in-progress/tests/collections/list/list-unify-any-elem/tests/2.list-unify-any-elem
  src/main/k/in-progress/tests/collections/list/list-unify-any-elem/tests/2.output.golden
  src/main/k/in-progress/tests/collections/list/list-unify-any-elem/tests/3.list-unify-any-elem
  src/main/k/in-progress/tests/collections/list/list-unify-any-elem/tests/3.output.golden
  src/main/k/in-progress/tests/collections/set/set-unify-concrete-2/Makefile
  src/main/k/in-progress/tests/collections/set/set-unify-concrete-2/set-unify-concrete-2.k
  src/main/k/in-progress/tests/collections/set/set-unify-concrete-2/tests/1.output.golden
  src/main/k/in-progress/tests/collections/set/set-unify-concrete-2/tests/1.set-unify-concrete-2
  src/main/k/in-progress/tests/collections/set/set-unify-concrete-2/tests/2.output.golden
  src/main/k/in-progress/tests/collections/set/set-unify-concrete-2/tests/2.set-unify-concrete-2
  src/main/k/in-progress/tests/collections/set/set-unify-concrete-2/tests/3.output.golden
  src/main/k/in-progress/tests/collections/set/set-unify-concrete-2/tests/3.set-unify-concrete-2
Labels: current iteration

#526 Label graph edges
  kore/src/Kore/Exec.hs
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/OnePath/Verification.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/Search.hs
  kore/src/Kore/Step/Strategy.hs
  kore/src/Kore/Step/Transition.hs
  kore/test/Test/Kore/OnePath/Step.hs
  kore/test/Test/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Strategy.hs
Labels: current iteration, feature

#539 repl: node labels
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration, feature

#541 More work on tests and test support functions.
  kore/test/Test/Kore/Error.hs
  kore/test/Test/Kore/IndexedModule/Error.hs
  kore/test/Test/Terse.hs
Labels: current iteration

#544 Feature/repl dump output to file
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration, feature

#542 Simplify Resolver error tests (IndexedModule error handling and test cleanup)
  kore/test/Test/Kore/Comparators.hs
  kore/test/Test/Kore/IndexedModule/Resolvers.hs
Labels: current iteration

#550 repl: step skips evaluated nodes
  kore/src/Kore/Repl/Interpreter.hs
Labels: current iteration, feature

#551 Label transitions in execution graph
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Axiom/UserDefined.hs
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Step/Strategy.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Comparators.hs
  kore/test/Test/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Strategy.hs
Labels: current iteration, feature

#532 Modularize tests by moving common functionality into `include.mk`
  src/main/k/working/function-evaluation-demo/Makefile
  src/main/k/working/imp-concrete-heat-cool/Makefile
  src/main/k/working/imp-concrete-state/Makefile
  src/main/k/working/imp-map-strict/Makefile
  src/main/k/working/imp-map-unify-strict/Makefile
  src/main/k/working/imp-map-unify/Makefile
  src/main/k/working/imp-map/Makefile
  src/main/k/working/imp-monosorted/Makefile
  src/main/k/working/imp/Makefile
  src/main/k/working/imp/tests/impossible-branch.psearch.final.output.golden
  src/main/k/working/imp/tests/impossible-branch.search.final.output.golden
  src/main/k/working/include.mk
  src/main/k/working/search/Makefile
  src/main/k/working/search/tests/initial.search.final.initial.output.golden
  src/main/k/working/search/tests/initial.search.final.output.golden
  src/main/k/working/search/tests/initial.search.final.unreachable.output.golden
  src/main/k/working/search/tests/initial.search.one.initial.output.golden
  src/main/k/working/search/tests/initial.search.one.output.golden
  src/main/k/working/search/tests/initial.search.one.unreachable.output.golden
  src/main/k/working/search/tests/initial.search.plus.initial.output.golden
  src/main/k/working/search/tests/initial.search.plus.output.golden
  src/main/k/working/search/tests/initial.search.plus.unreachable.output.golden
  src/main/k/working/search/tests/initial.search.star.initial.output.golden
  src/main/k/working/search/tests/initial.search.star.output.golden
  src/main/k/working/search/tests/initial.search.star.unreachable.output.golden
  src/main/k/working/smc/Makefile
  src/main/k/working/tests/bitrange/Makefile
  src/main/k/working/tests/collections/list-map-unify-concrete/Makefile
  src/main/k/working/tests/collections/list-requires/Makefile
  src/main/k/working/tests/collections/list-unify-concrete/Makefile
  src/main/k/working/tests/collections/list-unify-first-elem/Makefile
  src/main/k/working/tests/collections/list-unify-framing-variable-left/Makefile
  src/main/k/working/tests/collections/list-unify-framing-variable-right/Makefile
  src/main/k/working/tests/collections/list-unify-last-elem/Makefile
  src/main/k/working/tests/collections/map-lookup/Makefile
  src/main/k/working/tests/collections/map-unify-concrete/Makefile
  src/main/k/working/tests/collections/map-unify-framing-variable/Makefile
  src/main/k/working/tests/collections/set-unify-concrete/Makefile
  src/main/k/working/tests/collections/set-unify-framing-variable/Makefile
  src/main/k/working/tests/eqtest/Makefile
  src/main/k/working/tests/itetest/Makefile
  src/main/k/working/tests/kprove/Makefile
  src/main/k/working/tests/ord/Makefile
  src/main/k/working/tests/owise-1/Makefile
  src/main/k/working/tests/smt-lemma/Makefile
  src/main/k/working/tests/smt-lemma/prove/one-spec.k
  src/main/k/working/tests/smt-lemma/smt-lemma.k
  src/main/k/working/tests/smt-lemma/tests/1.smt-lemma
  src/main/k/working/tests/smt-lemma/tests/2.smt-lemma
  src/main/k/working/tests/smt-lemma/tests/3.smt-lemma
  src/main/k/working/tests/strict/Makefile
Labels: current iteration

#556 repl: fix step
  kore/src/Kore/Repl/Interpreter.hs
Labels: bug, current iteration

#555 Change "sort not declared" to "sort not defined"
  kore/src/Kore/IndexedModule/Error.hs
  kore/src/Kore/IndexedModule/Resolvers.hs
  kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/Imports.hs
  kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/PatternVerifier.hs
  kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/SortUsage.hs
  kore/test/Test/Kore/IndexedModule/Resolvers.hs
Labels: current iteration

#547 include.mk: Export variables for sub-makes
  include.mk
Labels: current iteration

#554 Keep removal predicate out of the term
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/Predicate/Predicate.hs
  kore/src/Kore/Step/Representation/ExpandedPattern.hs
  kore/src/Kore/Step/Representation/PredicateSubstitution.hs
  kore/src/Kore/Step/Representation/Predicated.hs
  kore/src/Kore/Step/Step.hs
Labels: current iteration

#552 repl: stepf through branchings
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration, feature

#559 repl: rule command test
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration

#546 Basic all path tests
  src/main/k/in-progress/all-path/00-basic/00-no-rules/Makefile
  src/main/k/in-progress/all-path/00-basic/00-no-rules/notprovable/distinct-spec.k
  src/main/k/in-progress/all-path/00-basic/00-no-rules/path.k
  src/main/k/in-progress/all-path/00-basic/00-no-rules/provable/identity-spec.k
  src/main/k/in-progress/all-path/00-basic/01-one-rule/Makefile
  src/main/k/in-progress/all-path/00-basic/01-one-rule/notprovable/all-path-c-spec.k
  src/main/k/in-progress/all-path/00-basic/01-one-rule/path.k
  src/main/k/in-progress/all-path/00-basic/01-one-rule/provable/all-path-b-or-c-spec.k
  src/main/k/in-progress/all-path/00-basic/01-one-rule/provable/all-path-b-spec.k
  src/main/k/in-progress/all-path/00-basic/02-cyclic-rule/Makefile
  src/main/k/in-progress/all-path/00-basic/02-cyclic-rule/path.k
  src/main/k/in-progress/all-path/00-basic/02-cyclic-rule/provable/all-path-b-spec.k
  src/main/k/in-progress/all-path/00-basic/02-cyclic-rule/provable/all-path-c-spec.k
  src/main/k/in-progress/all-path/00-basic/03-concurrent-rules/Makefile
  src/main/k/in-progress/all-path/00-basic/03-concurrent-rules/notprovable/all-path-b-spec.k
  src/main/k/in-progress/all-path/00-basic/03-concurrent-rules/path.k
  src/main/k/in-progress/all-path/00-basic/03-concurrent-rules/provable/all-path-b-or-c-spec.k
  src/main/k/in-progress/all-path/00-basic/03-concurrent-rules/provable/one-path-b-spec.k
  src/main/k/in-progress/all-path/00-basic/04-different-length/Makefile
  src/main/k/in-progress/all-path/00-basic/04-different-length/path.k
  src/main/k/in-progress/all-path/00-basic/04-different-length/provable/all-path-f-spec.k
  src/main/k/in-progress/all-path/02-constructors/00-case-analysis/Makefile
  src/main/k/in-progress/all-path/02-constructors/00-case-analysis/notprovable/all-path-end-spec.k
  src/main/k/in-progress/all-path/02-constructors/00-case-analysis/path.k
  src/main/k/in-progress/all-path/02-constructors/00-case-analysis/provable/all-path-end-spec.k
  src/main/k/in-progress/all-path/03-unification/set-select/Makefile
  src/main/k/in-progress/all-path/03-unification/set-select/notprovable/all-path-b-or-c-spec.k
  src/main/k/in-progress/all-path/03-unification/set-select/notprovable/all-path-b-spec.k
  src/main/k/in-progress/all-path/03-unification/set-select/path.k
  src/main/k/in-progress/all-path/03-unification/set-select/provable/all-path-b-or-c-spec.k
  src/main/k/in-progress/all-path/03-unification/set-select/provable/one-path-b-or-c-spec.k
  src/main/k/in-progress/all-path/03-unification/set-select/provable/one-path-b-spec.k
  src/main/k/in-progress/all-path/03-unification/set-select/provable/one-path-c-spec.k
  src/main/k/in-progress/all-path/limitations/interfering-specs/Makefile
  src/main/k/in-progress/all-path/limitations/interfering-specs/notprovable/all-path-a-c-b-d-spec.k
  src/main/k/in-progress/all-path/limitations/interfering-specs/path.k
  src/main/k/in-progress/all-path/limitations/interfering-specs/provable/all-path-a-c-spec.k
  src/main/k/in-progress/all-path/limitations/interfering-specs/provable/all-path-b-d-spec.k
Labels: current iteration

#557 Feature/repl attempt rule
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration, feature

#540 First version of all path reachability design doc
  docs/2019-03-28-All-Path-Reachability-Proofs.md
  docs/reachability-symbols.md
Labels: current iteration

#529 Smt sorts
  kore/src/Kore/AST/PureToKore.hs
  kore/src/Kore/ASTVerifier/DefinitionVerifier.hs
  kore/src/Kore/Attribute/Axiom.hs
  kore/src/Kore/Attribute/Axiom/Concrete.hs
  kore/src/Kore/Attribute/Axiom/Constructor.hs
  kore/src/Kore/Debug.hs
  kore/src/Kore/IndexedModule/IndexedModule.hs
  kore/src/Kore/Step/SMT/Encoder.hs
  kore/src/Kore/Step/SMT/Lemma.hs
  kore/src/Kore/Step/SMT/Sorts.hs
  kore/src/SMT.hs
  kore/src/SimpleSMT.hs
  kore/test/Test/Kore/Step/SMT/Sorts.hs
Labels: current iteration

#558 Non-deterministic one-path proofs
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/OnePath/Verification.hs
  kore/src/Kore/Repl/Interpreter.hs
Labels: current iteration

#560 Allow branching in And.makeEvaluate
  kore/src/Kore/Step/Simplification/And.hs
  kore/src/Kore/Step/Substitution.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
Labels: current iteration

#561 No function remainders
  kore/src/Kore/Step/Axiom/Data.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Axiom/Registry.hs
Labels: current iteration, feature

#565 repl: add index attribute + print index in showRule + bug fix in try
  kore/src/Kore/Attribute/Axiom.hs
  kore/src/Kore/Attribute/RuleIndex.hs
  kore/src/Kore/OnePath/Verification.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
Labels: current iteration, feature

#566 Use constructor symbols in the SMT.
  kore/src/Kore/IndexedModule/MetadataTools.hs
  kore/src/Kore/Step/SMT/Lemma.hs
  kore/src/Kore/Step/SMT/Symbols.hs
  kore/src/Kore/Step/SMT/Translate.hs
  kore/src/SMT.hs
  kore/test/Test/Kore/Builtin/List.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/IndexedModule/MockMetadataTools.hs
  kore/test/Test/Kore/OnePath/Step.hs
  kore/test/Test/Kore/OnePath/Verification.hs
  kore/test/Test/Kore/Proof/Value.hs
  kore/test/Test/Kore/Step.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
  kore/test/Test/Kore/Step/Axiom/UserDefined.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/PatternAttributes.hs
  kore/test/Test/Kore/Step/SMT/Builders.hs
  kore/test/Test/Kore/Step/SMT/Helpers.hs
  kore/test/Test/Kore/Step/SMT/Sorts.hs
  kore/test/Test/Kore/Step/SMT/Symbols.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/Application.hs
  kore/test/Test/Kore/Step/Simplification/Ceil.hs
  kore/test/Test/Kore/Step/Simplification/DomainValue.hs
  kore/test/Test/Kore/Step/Simplification/Equals.hs
  kore/test/Test/Kore/Step/Simplification/Exists.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
  kore/test/Test/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Substitution.hs
  kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
  kore/test/Test/Kore/Unification/Unifier.hs
Labels: current iteration, feature

#562 Simplifying one-path tests for use in upcoming all-paths work
  kore/test/Test/Kore/Step.hs
Labels: current iteration

#564 Feature/monad unify
  kore/src/Kore/ASTPrettyPrint.hs
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Logger.hs
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/Axiom/UserDefined.hs
  kore/src/Kore/Step/Error.hs
  kore/src/Kore/Step/Search.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs-boot
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/Step/Substitution.hs-boot
  kore/src/Kore/Unification/Error.hs
  kore/src/Kore/Unification/Procedure.hs
  kore/src/Kore/Unification/UnifierImpl.hs
  kore/src/Kore/Unification/Unify.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Comparators.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Substitution.hs
  kore/test/Test/Kore/Unification/Unifier.hs
Labels: current iteration, feature

#575 Make Haddock fail
  Makefile
  include.mk
  kore/src/Kore/Repl/Interpreter.hs
Labels: current iteration

#568 Encapsulate StepPatternSimplifier
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Axiom/UserDefined.hs
  kore/src/Kore/Step/Condition/Evaluator.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/Simplification/Application.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Simplification/ExpandedPattern.hs
  kore/src/Kore/Step/Simplification/Pattern.hs
  kore/src/Kore/Step/Simplification/Predicate.hs
  kore/src/Kore/Step/Simplification/Simplifier.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Step/MockSimplifiers.hs
  kore/test/Test/Kore/Step/Simplifier.hs
Labels: current iteration

#567 All-path reachability claims
  kore/src/Kore/AllPath.hs
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/OnePath/Verification.hs
  kore/src/Kore/Step/Strategy.hs
  kore/test/Test/Kore/AllPath.hs
  kore/test/Test/Kore/Comparators.hs
Labels: current iteration, feature

#584 Repl clear
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: bug, current iteration, feature

#581 Repl first failed unification
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Unification/Unify.hs
Labels: current iteration, feature

#592 SMT: Use default logic
  kore/src/SMT.hs
Labels: current iteration

#582 Simplify \exists with bound substitutions
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Predicate/Predicate.hs
  kore/src/Kore/Step/Pattern.hs
  kore/src/Kore/Step/Representation/ExpandedPattern.hs
  kore/src/Kore/Step/Representation/PredicateSubstitution.hs
  kore/src/Kore/Step/Representation/Predicated.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/Unification/Substitution.hs
  kore/src/Kore/Unification/SubstitutionNormalization.hs
  kore/test/Test/Kore/Step/Simplification/Exists.hs
  kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
  kore/test/Test/Kore/Step/Substitution.hs
  kore/test/Test/Kore/Unification/Substitution.hs
  kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
Labels: bug, current iteration

#590 repl: pipe command
  kore/package.yaml
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: current iteration, feature

#593 Quantify remainder variables
  kore/src/Kore/ASTPrettyPrint.hs
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Remainder.hs
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Unification/Error.hs
  kore/test/Test/Kore/Comparators.hs
  kore/test/Test/Kore/Step/Remainder.hs
  kore/test/Test/Kore/Step/Step.hs
Labels: current iteration, feature

#585 Distinguish \bottom unifier and \bottom result
  kore/src/Kore/OnePath/Step.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Axiom/UserDefined.hs
  kore/src/Kore/Step/Result.hs
  kore/src/Kore/Step/Simplification/And.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Step/Step.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
  kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
  kore/test/Test/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Substitution.hs
Labels: bug, current iteration

#594 Keep \not predicates
  kore/src/Kore/Step/Simplification/Equals.hs
  kore/src/Kore/Step/Simplification/Iff.hs
  kore/src/Kore/Step/Simplification/Implies.hs
  kore/src/Kore/Step/Simplification/Not.hs
  kore/src/Kore/Step/Simplification/Pattern.hs
  kore/test/Test/Kore/Step/Simplification/Iff.hs
  kore/test/Test/Kore/Step/Simplification/Not.hs
Labels: bug, current iteration
