Repository runtimeverification/haskell-backend, pull requests merged in 2020-04, with the labels that each got.

#1701 Added SMT conversion for int and bool existential quantifiers
  kore/src/Kore/Step/SMT/Evaluator.hs
  kore/src/Kore/Step/SMT/Lemma.hs
  kore/src/Kore/Step/SMT/Translate.hs
  kore/src/SMT.hs
  kore/src/SMT/SimpleSMT.hs
  kore/test/Test/Kore.hs
  kore/test/Test/Kore/Step/SMT/Evaluator.hs
  kore/test/Test/Kore/Step/SMT/Symbols.hs
  kore/test/Test/Kore/Step/SMT/Translate.hs
  test/issue-1639/Makefile
  test/issue-1639/h.k
  test/issue-1639/h1-spec.k
  test/issue-1639/h1-spec.k.out.golden
  test/issue-1639/h2-spec.k
  test/issue-1639/h2-spec.k.out.golden
  test/issue-1639/h3-spec.k
  test/issue-1639/h3-spec.k.out.golden
  test/issue-1639/h4-spec.k
  test/issue-1639/h4-spec.k.out.golden
Labels: automerge

#1706 Bug: List concat unification
  kore/src/Kore/Builtin/List.hs
  kore/test/Test/Kore/Builtin/List.hs
Labels: automerge

#1727 Prelude.Kore (partitionEithers, unless, when)
  kore/src/Kore/ASTVerifier/PatternVerifier.hs
  kore/src/Kore/ASTVerifier/SentenceVerifier.hs
  kore/src/Kore/Attribute/Axiom/Concrete.hs
  kore/src/Kore/Attribute/Hook.hs
  kore/src/Kore/Attribute/Parser.hs
  kore/src/Kore/Attribute/Priority.hs
  kore/src/Kore/Attribute/ProductionID.hs
  kore/src/Kore/Attribute/Smtlib/Smthook.hs
  kore/src/Kore/Attribute/SortInjection.hs
  kore/src/Kore/Attribute/Symbol/Klabel.hs
  kore/src/Kore/Builtin/AssociativeCommutative.hs
  kore/src/Kore/Builtin/Endianness.hs
  kore/src/Kore/Builtin/InternalBytes.hs
  kore/src/Kore/Builtin/Signedness.hs
  kore/src/Kore/Builtin/Verifiers.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Parser/Lexeme.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/EquationalStep.hs
  kore/src/Kore/Step/SMT/Declaration/Sorts.hs
  kore/src/Kore/Step/Simplification/And.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/src/Prelude/Kore.hs
  kore/src/SQL/SOP.hs
  kore/test/Test/ConsistentKore.hs
  kore/test/Test/Data/Sup.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Exec.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Variables/Fresh.hs
Labels: automerge

#1728 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1712 test/set/set-iteration: Test symbolic iteration
  test/set/set-iteration/test-2-spec.k
  test/set/set-iteration/test-2-spec.k.out.golden
Labels: automerge

#1732 Remove SMT.AST.appendToEncoding
  kore/src/Kore/Step/SMT/AST.hs
  kore/src/Kore/Step/SMT/Representation/Sorts.hs
Labels: automerge

#1736 Prelude.Kore (Typeable)
  kore/src/Data/Sup.hs
  kore/src/Debug.hs
  kore/src/Kore/IndexedModule/OverloadGraph.hs
  kore/src/Kore/IndexedModule/SortGraph.hs
  kore/src/Kore/Internal/Conditional.hs
  kore/src/Kore/Internal/Inj.hs
  kore/src/Kore/Log/DebugAxiomEvaluation.hs
  kore/src/Kore/Log/DebugSkipSimplification.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/WarnFunctionWithoutEvaluators.hs
  kore/src/Kore/Sort.hs
  kore/src/Kore/Step/Strategy.hs
  kore/src/Kore/Step/Transition.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/src/Log/Entry.hs
  kore/src/Prelude/Kore.hs
  kore/src/SQL.hs
  kore/src/SQL/SOP.hs
  kore/src/SQL/Table.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
Labels: appetite: S

#1737 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1744 logEntry: Add context to log message
  kore/src/Log.hs
Labels: automerge, bug

#1743 Do not log SMT models
  kore/src/SMT/SimpleSMT.hs
Labels: automerge

#1741 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1747 Fix bug in repl-script Makefile rule
  test/include.mk
Labels: automerge

#1746 Remove old equation application code
  kore/CHANGELOG.md
  kore/ChangeLog.md
  kore/package.yaml
  kore/src/Kore/Log.hs
  kore/src/Kore/Log/DebugAppliedRule.hs
  kore/src/Kore/Log/DebugAxiomEvaluation.hs
  kore/src/Kore/Log/DebugSkipSimplification.hs
  kore/src/Kore/Log/KoreLogOptions.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/SQLite.hs
  kore/src/Kore/Step/Axiom/Evaluate.hs
  kore/src/Kore/Step/EqualityPattern.hs
  kore/src/Kore/Step/EquationalStep.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/test/Test/Kore/Log/DebugAppliedRule.hs
  kore/test/Test/Kore/Log/DebugSkipSimplification.hs
  kore/test/Test/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Step/Axiom/Evaluate.hs
  kore/test/Test/Kore/Step/EquationalStep.hs
Labels: automerge

#1751 Recursing renormalize and some debugging info
  kore/src/Kore/AST/AstWithLocation.hs
  kore/src/Kore/Attribute/SourceLocation.hs
  kore/src/Kore/Builtin.hs
  kore/src/Kore/Builtin/Endianness/Endianness.hs
  kore/src/Kore/Builtin/Signedness/Signedness.hs
  kore/src/Kore/Equation/Application.hs
  kore/src/Kore/Equation/Equation.hs
  kore/src/Kore/Internal/Alias.hs
  kore/src/Kore/Internal/Symbol.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
  kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/PatternVerifier.hs
Labels: automerge

#1745 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1756 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1759 Added task for verifying definitions
  include.mk
  test/include.mk
Labels: automerge

#1761 Refactor hooked functions
  kore/src/Kore/Builtin.hs
  kore/src/Kore/Builtin/AssociativeCommutative.hs
  kore/src/Kore/Builtin/Bool.hs
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Builtin/Int.hs
  kore/src/Kore/Builtin/InternalBytes.hs
  kore/src/Kore/Builtin/KEqual.hs
  kore/src/Kore/Builtin/Krypto.hs
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Builtin/String.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
Labels: automerge

#1758 New names for crypto hooks
  kore/src/Kore/Builtin/Krypto.hs
  kore/test/Test/Kore/Builtin/Krypto.hs
Labels: automerge

#1764 Update dependency: deps/k_release
  deps/k_release
  include.mk
Labels: automerge

#1773 SubstitutionCoverageError: Report unassigned variables
  kore/src/Kore/Log/ErrorRewritesInstantiation.hs
Labels: automerge

#1714 Concrete implementation of ==K hook; internal simplification rules
  kore/src/Kore/Builtin/Bool.hs
  kore/src/Kore/Builtin/KEqual.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Builtin/KEqual.hs
  test/not-kequal/Makefile
  test/not-kequal/a.test
  test/not-kequal/a.test.out.golden
  test/not-kequal/test.k
Labels: automerge

#1769 Add help messages for log entries
  kore/src/Kore/Equation/Application.hs
  kore/src/Kore/Log/DebugAppliedRewriteRules.hs
  kore/src/Kore/Log/DebugEvaluateCondition.hs
  kore/src/Kore/Log/DebugProofState.hs
  kore/src/Kore/Log/DebugSolver.hs
  kore/src/Kore/Log/ErrorException.hs
  kore/src/Kore/Log/ErrorRewritesInstantiation.hs
  kore/src/Kore/Log/InfoAttemptUnification.hs
  kore/src/Kore/Log/InfoReachability.hs
  kore/src/Kore/Log/KoreLogOptions.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/WarnBottomHook.hs
  kore/src/Kore/Log/WarnDecidePredicateUnknown.hs
  kore/src/Kore/Log/WarnFunctionWithoutEvaluators.hs
  kore/src/Kore/Log/WarnSymbolSMTRepresentation.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Log/Entry.hs
Labels: automerge

#1782 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1777 Remove ToRulePattern, Part 1
  kore/app/exec/Main.hs
  kore/src/Kore/Attribute/Axiom.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log/DebugProofState.hs
  kore/src/Kore/Log/InfoReachability.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Step/Rule/Expand.hs
  kore/src/Kore/Step/Rule/Simplify.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/Rule.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Step/Rule/Expand.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
  kore/test/Test/Kore/Strategies/AllPath/Verification.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  kore/test/Test/Kore/Strategies/OnePath/Verification.hs
  kore/test/Test/Kore/Strategies/Reachability/Verification.hs
Labels: automerge

#1771 Add a distinguished type for rewrite rule variables
  kore/src/Kore/Log/DebugAppliedRewriteRules.hs
  kore/src/Kore/Log/ErrorRewritesInstantiation.hs
  kore/src/Kore/ModelChecker/Step.hs
  kore/src/Kore/Rewriting/RewritingVariable.hs
  kore/src/Kore/Rewriting/UnifyingRule.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/Remainder.hs
  kore/src/Kore/Step/RewriteStep.hs
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Variables/Fresh.hs
  kore/src/Kore/Variables/UnifiedVariable.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Rewriting/RewritingVariable.hs
  kore/test/Test/Kore/Step/Remainder.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Variables/Fresh.hs
Labels: automerge

#1762 Forbid injections into hooked sorts.
  Makefile
  kore/app/parser/Main.hs
  kore/src/Kore/ASTVerifier/AttributesVerifier.hs
  test/no-injection-into-hooked/Makefile
  test/no-injection-into-hooked/test.k
  test/no-injection-into-hooked/test.k.verify
  test/no-injection-into-hooked/test.k.verify.out.golden
Labels: automerge

#1783 kore-repl: Move alias scripts and add them to the package
  kore/data/kast.kscript
  kore/package.yaml
Labels: automerge
