Repository runtimeverification/haskell-backend, pull requests merged in 2020-03, with the labels that each got.

#1593 Repl: save partial proof command
  include.mk
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Strategies/Verification.hs
  test/tiny/run-one-save-state-repl-script-spec.k.repl
  test/tiny/save-config-repl-script-spec-k.repl
  test/tiny/test-a-to-c-spec.kore
  test/tiny/test-a-to-c-vdefinition.kore
  test/tiny/test-save-partial-proof.sh
  test/tiny/test-save-partial-proof.sh.out.golden
  test/tiny/tiny.k
Labels: automerge

#1609 Add a "release" flag
  kore/package.yaml
Labels: meta

#1612 Make values irrelevant to Map key membership
  kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
  kore/src/Kore/Domain/Builtin.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Syntax/ElementVariable.hs
  kore/src/Kore/Syntax/SetVariable.hs
  kore/src/Kore/Syntax/Variable.hs
  kore/test/Test/Kore/Builtin/AssocComm/CeilSimplifier.hs
  test/imp/2.merge.out.golden
  test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
Labels: automerge

#1613 Kore.Log.withAsyncLogAction: Raise exceptions in main thread
  Jenkinsfile
  kore/src/Kore/Log.hs
Labels: automerge

#1620 Replace Data.List.nub with Data.Containers.ListUtils.nubOrd in makeMultipleAnd(/Or)Predicate.
  kore/src/Kore/Internal/Predicate.hs
Labels: automerge

#1607 Command line option to turn warnings into errors
  kore/src/Kore/Log.hs
  kore/src/Kore/Log/KoreLogOptions.hs
Labels: automerge

#1621 Add logWhile method to MonadLog
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Transition.hs
  kore/src/ListT.hs
  kore/src/Log.hs
  kore/src/SMT.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
Labels: automerge

#1616 Evaluate in hook for symbolic sets
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Domain/Builtin.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Builtin/Set.hs
Labels: automerge

#1633 Repl: add new aliases to kast.kscript with directory argument
  dist/kast.kscript
Labels: automerge

#1617 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1624 Print command line and KORE_EXEC_OPTS when parsing fails
  kore/app/exec/Main.hs
  kore/app/format/Main.hs
  kore/app/parser/Main.hs
  kore/app/repl/Main.hs
  kore/app/share/GlobalMain.hs
Labels: automerge

#1634 Use ActualEntry instead of SomeEntry in the logger
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log.hs
  kore/src/Kore/Log/DebugSolver.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Log.hs
  kore/src/Log/Entry.hs
  kore/src/SMT.hs
  kore/src/SMT/SimpleSMT.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
Labels: automerge

#1635 Define inequality of Bytes
  kore/src/Kore/Step/Simplification/AndTerms.hs
Labels: automerge

#1622 Better identification for rewrite rules based on priority
  kore/Makefile
  kore/src/Kore/Attribute/Axiom.hs
  kore/src/Kore/Step/EqualityPattern.hs
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/test/Test/Kore/Exec.hs
  kore/test/Test/Kore/Step/Rule.hs
  test/setvars/setvars.k
Labels: automerge

#1641 Change Pretty instance for DebugAppliedRewriteRules and DebugProofState
  kore/src/Kore/Log/DebugAppliedRewriteRules.hs
  kore/src/Kore/Log/DebugProofState.hs
Labels: automerge

#1632 Clean-up after Map and Set definedness changes
  kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
  test/imp/2.merge.out.golden
  test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
Labels: automerge

#1646 Replace WarnSimplificationWithRemainder with DebugSkipSimplification
  kore/src/Kore/Log/DebugSkipSimplification.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/SQLite.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Log/DebugSkipSimplification.hs
  test/simplification/Makefile
Labels: automerge

#1644 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1651 Concrete axiom attribute
  kore/src/Kore/ASTVerifier/SentenceVerifier.hs
  kore/src/Kore/Attribute/Axiom.hs
  kore/src/Kore/Attribute/Axiom/Concrete.hs
  kore/src/Kore/Attribute/Parser.hs
  kore/src/Kore/Attribute/Pattern/FreeVariables.hs
  kore/src/Kore/Step/EqualityPattern.hs
  kore/src/Kore/Syntax/Sentence.hs
  kore/test/Test/Kore/Attribute/Axiom/Concrete.hs
  kore/test/Test/Kore/Step/Axiom/Evaluate.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/Rule.hs
Labels: automerge

#1658 Update dependency: deps/k_release
  deps/k_release
  test/imp/sum-save-proofs-spec.k.save-proofs.kore.golden
  test/save-proofs/Makefile
  test/save-proofs/test-1-spec.k.save-proofs.kore.golden
Labels: automerge

#1663 Nix expressions
  .gitignore
  README.md
  default.nix
  nix/ghcide.nix
  nix/sources.json
  nix/sources.nix
  nix/stylish-haskell.nix
  shell.nix
Labels: automerge

#1673 Replace "K framework" with "Kore" for " --version"
  kore/app/share/GlobalMain.hs
Labels: automerge

#1670 Refactor UnificationProcedure
  kore/src/Kore/Log/ErrorRewritesInstantiation.hs
  kore/src/Kore/Log/InfoAttemptUnification.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/ModelChecker/Step.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/EquationalStep.hs
  kore/src/Kore/Step/RewriteStep.hs
  kore/src/Kore/Step/Search.hs
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Unification/Procedure.hs
  kore/src/Kore/Unification/UnificationProcedure.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Unification/Unifier.hs
Labels: automerge

#1659 Keep Bottom nodes in the execution graph
  kore/src/Kore/Strategies/Goal.hs
  test/assume/Makefile
  test/assume/test-spec.k
  test/assume/test-spec.k.out.golden
  test/assume/test.k
Labels: automerge

#1652 Add options to kore-repl as in kore-exec
  kore/app/repl/Main.hs
  kore/src/Kore/Log.hs
Labels: automerge

#1681 Return stuck goal after remove destination
  kore/src/Kore/Strategies/Goal.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  test/imp/sum-save-proofs-spec.k.out.golden
Labels: automerge

#1662 Update dependency: deps/k_release
  deps/k_release
  test/k-equal/iszero-ge-spec.k.out.golden
  test/k-equal/iszero-gt-spec.k.out.golden
Labels: automerge

#1685 implemented substitution checks for concrete and symbolic attributes
  kore/src/Kore/Attribute/Axiom/Concrete.hs
  kore/src/Kore/Step/Axiom/Evaluate.hs
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/EqualityPattern.hs
  kore/src/Kore/Step/EquationalStep.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/Axiom/Evaluate.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
Labels: automerge

#1692 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1693 Evaluate BOOL.and by unification
  kore/src/Kore/Builtin/Bool.hs
  kore/src/Kore/Internal/Condition.hs
  kore/src/Kore/Internal/Conditional.hs
  kore/src/Kore/Internal/Symbol.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Builtin/Bool.hs
  test/bmc/fail-3-bmc-spec.k.out.golden
  test/bmc/fail-4-bmc-spec.k.out.golden
  test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
  test/symbolic-ensures/1.strict.out.golden
Labels: automerge

#1705 Continue #1682: Implement shortDoc for InfoReachability
  kore/src/Kore/Log/InfoReachability.hs
Labels: automerge

#1707 default.nix: Add profiling flag
  default.nix
Labels: automerge

#1703 LoggerT: Keep an explicit context stack instead of a closure
  kore/app/exec/Main.hs
  kore/app/parser/Main.hs
  kore/app/repl/Main.hs
  kore/app/share/GlobalMain.hs
  kore/bench/exec/Main.hs
  kore/src/Kore/Log.hs
  kore/src/Kore/Log/DebugSolver.hs
  kore/src/Log.hs
  kore/src/SMT.hs
  kore/src/SMT/SimpleSMT.hs
  kore/test/Test/Kore/Builtin/Bool.hs
  kore/test/Test/Kore/Builtin/Endianness.hs
  kore/test/Test/Kore/Builtin/Krypto.hs
  kore/test/Test/Kore/Builtin/Signedness.hs
  kore/test/Test/Kore/Exec.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Step/Rule/Combine.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Unification/Unifier.hs
  kore/test/Test/SMT.hs
Labels: performance

#1696 Update dependency: deps/k_release
  deps/k_release
  test/imp-concrete-heat-cool/imp.k
  test/imp-concrete-state/imp.k
  test/imp-map-strict/imp.k
  test/imp-map-unify-strict/imp.k
  test/imp-map-unify/imp.k
  test/imp-map/imp.k
  test/imp-monosorted/imp.k
Labels: automerge
