Repository runtimeverification/haskell-backend, pull requests merged in 2020-01, with the labels that each got.

#1380 Update dependencies
  deps/k_release
Labels: automerge

#1388 Fix map matching with opaque on the right.
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
  src/main/k/working/tests/with-config-arbitrary-map/Makefile
  src/main/k/working/tests/with-config-arbitrary-map/prove/one-spec.k
  src/main/k/working/tests/with-config-arbitrary-map/with-config.k
Labels: automerge

#1355 Single result evaluation for functions
  design-decisions/2020-01-02-Side-conditions-for-predicates.md
  kore/src/Kore/Exec.hs
  kore/src/Kore/ModelChecker/Simplification.hs
  kore/src/Kore/ModelChecker/Step.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/Axiom/Evaluate.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/EquationalStep.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/RewriteStep.hs
  kore/src/Kore/Step/Rule/Combine.hs
  kore/src/Kore/Step/Rule/Simplify.hs
  kore/src/Kore/Step/Search.hs
  kore/src/Kore/Step/Simplification/Application.hs
  kore/src/Kore/Step/Simplification/Condition.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Step/Simplification/OrPattern.hs
  kore/src/Kore/Step/Simplification/Pattern.hs
  kore/src/Kore/Step/Simplification/Rule.hs
  kore/src/Kore/Step/Simplification/Simplify.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Unification/Procedure.hs
  kore/src/Kore/Unification/SubstitutionSimplifier.hs
  kore/src/Kore/Unification/UnifierImpl.hs
  kore/src/Kore/Unification/UnifierT.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Step/Axiom/Evaluate.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/Axiom/Registry.hs
  kore/test/Test/Kore/Step/EquationalStep.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Step/Simplification/Condition.hs
  kore/test/Test/Kore/Step/Simplification/Exists.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  kore/test/Test/Kore/Step/Simplification/IntegrationProperty.hs
  kore/test/Test/Kore/Step/Simplification/Pattern.hs
  kore/test/Test/Kore/Unification/Unifier.hs
  kore/test/Test/Kore/Unification/UnifierT.hs
Labels: automerge

#1401 Add LogMessage to the Registry
  kore/app/share/GlobalMain.hs
  kore/src/Kore/Logger/Registry.hs
Labels: bug

#1386 Catch and log errors
  kore/app/exec/Main.hs
  kore/src/Kore/Logger.hs
  kore/src/Kore/Logger/CriticalExecutionError.hs
  kore/src/Kore/Logger/Registry.hs
Labels: automerge

#1392 Log each condition sent to Z3
  kore/src/Kore/Attribute/Pattern/Created.hs
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Logger/InfoEvaluateCondition.hs
  kore/src/Kore/Logger/Registry.hs
  kore/src/Kore/Step/SMT/Evaluator.hs
  src/main/k/working/imp/merge/2.merge-golden
Labels: automerge

#1397 Update dependencies
  deps/k_release
Labels: automerge

#1398 Fix ConstructorLike for maps
  kore/src/Kore/Attribute/Pattern.hs
  kore/src/Kore/Attribute/Pattern/ConstructorLike.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
  kore/test/Test/Kore/Attribute/Pattern/ConstructorLike.hs
  kore/test/Test/Kore/Step/Simplification/Ceil.hs
Labels: automerge

#1406 Configureable timestamps in log
  kore/src/Kore/Logger/Output.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge

#1366 Add design doc for ?X with ensures
  docs/2019-12-16-Question-Mark-Variables-With-Ensures.md
Labels: automerge

#1411 Strip `Evaluated` from arguments in `functionEvaluator`
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/test/Test/Kore/Builtin/Int.hs
Labels: automerge

#1422 Fixed no-helpers found bug
  test/include.mk
  test/regression-evm-semantics-39dd1e5/Makefile
  test/regression-wasm-semantics-840390f/Makefile
Labels: automerge, bug

#1419 Refactor logging
  kore/app/exec/Main.hs
  kore/app/parser/Main.hs
  kore/app/repl/Main.hs
  kore/app/share/GlobalMain.hs
  kore/bench/exec/Main.hs
  kore/src/Branch.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log.hs
  kore/src/Kore/Log/CriticalExecutionError.hs
  kore/src/Kore/Log/DebugAppliedRewriteRules.hs
  kore/src/Kore/Log/DebugAppliedRule.hs
  kore/src/Kore/Log/DebugAxiomEvaluation.hs
  kore/src/Kore/Log/DebugProofState.hs
  kore/src/Kore/Log/DebugSolver.hs
  kore/src/Kore/Log/InfoEvaluateCondition.hs
  kore/src/Kore/Log/KoreLogOptions.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/WarnBottomHook.hs
  kore/src/Kore/Log/WarnFunctionWithoutEvaluators.hs
  kore/src/Kore/Log/WarnSimplificationWithRemainder.hs
  kore/src/Kore/ModelChecker/Bounded.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Step/Axiom/Evaluate.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/EquationalStep.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/RewriteStep.hs
  kore/src/Kore/Step/SMT/Evaluator.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Simplification/Simplify.hs
  kore/src/Kore/Step/Transition.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Unification/Procedure.hs
  kore/src/Kore/Unification/UnifierT.hs
  kore/src/ListT.hs
  kore/src/Log.hs
  kore/src/SMT.hs
  kore/src/SMT/SimpleSMT.hs
  kore/test/Test/Kore.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Step/Rule/Combine.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
Labels: automerge

#1423 include.mk: Disable builtin rules
  include.mk
Labels: automerge

#1394 Add HLint to Jenkins checks
  .hlint.yaml
  kore/app/exec/Main.hs
  kore/app/profiler/Main.hs
  kore/src/Kore/ASTVerifier/PatternVerifier.hs
  kore/src/Kore/ASTVerifier/Verifier.hs
  kore/src/Kore/Attribute/Priority.hs
  kore/src/Kore/Builtin/AssociativeCommutative.hs
  kore/src/Kore/Builtin/Endianness/Endianness.hs
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Signedness/Signedness.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Log.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Step/EquationalStep.hs
  kore/src/Kore/Step/RewriteStep.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/src/Kore/Step/SMT/Translate.hs
  kore/src/Kore/Step/Simplification/Application.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Step/Simplification/ExpandAlias.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Syntax/Inhabitant.hs
  kore/src/Kore/Unification/Error.hs
  kore/src/Kore/Unification/SubstitutionNormalization.hs
  kore/test/Test/ConsistentKore.hs
  kore/test/Test/Debug.hs
  kore/test/Test/Kore.hs
  kore/test/Test/Kore/Attribute/Sort/ConstructorsBuilder.hs
  kore/test/Test/Kore/Builtin/Krypto.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Exec.hs
  kore/test/Test/Kore/IndexedModule/SortGraph.hs
  kore/test/Test/Kore/Step/Axiom/Evaluate.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/Rule.hs
  kore/test/Test/Kore/Step/Rule/Expand.hs
  kore/test/Test/Kore/Step/SMT/Evaluator.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/Builtin.hs
  kore/test/Test/Kore/Step/Simplifier.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  kore/test/Test/Kore/Unification/Unifier.hs
  kore/test/Test/Kore/Unification/UnifierT.hs
  kore/test/Test/Kore/With.hs
  kore/test/Test/Terse.hs
  scripts/check.sh
Labels: automerge

#1434 Change the simplified bit to a sum
  kore/src/Kore/Attribute/Pattern/Simplified.hs
  kore/src/Kore/Builtin/Endianness/Endianness.hs
  kore/src/Kore/Builtin/Signedness/Signedness.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
Labels: automerge

#1426 hie.yaml: Use hie-bios.sh to setup mega-component cradle
  .gitignore
  README.md
  envrc.sh
  hie-bios.sh
  hie.yaml
  stack.yaml
Labels: automerge

#1430 Side conditions for substitution simplification
  kore/src/Kore/Builtin/KEqual.hs
  kore/src/Kore/Step/Remainder.hs
  kore/src/Kore/Step/Simplification/And.hs
  kore/src/Kore/Step/Simplification/AndPredicates.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Step/Simplification/Condition.hs
  kore/src/Kore/Step/Simplification/Equals.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Step/Simplification/Iff.hs
  kore/src/Kore/Step/Simplification/Implies.hs
  kore/src/Kore/Step/Simplification/Not.hs
  kore/src/Kore/Step/Simplification/Simplify.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Unification/SubstitutionSimplifier.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
  kore/test/Test/Kore/Step/Simplification/Iff.hs
  kore/test/Test/Kore/Step/Simplification/Implies.hs
  kore/test/Test/Kore/Step/Simplification/Not.hs
  kore/test/Test/Kore/Step/Simplification/SubstitutionSimplifier.hs
Labels: automerge

#1435 ConstructorLike is Simplified
  kore/src/Kore/Attribute/Pattern.hs
  kore/src/Kore/Attribute/Pattern/ConstructorLike.hs
  kore/src/Kore/Attribute/Pattern/Simplified.hs
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
Labels: automerge

#1438 Refactor Substitution
  docs/introduction.md
  kore/src/Kore/Internal/Condition.hs
  kore/src/Kore/Internal/Conditional.hs
  kore/src/Kore/Internal/Pattern.hs
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Internal/Substitution.hs
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/EquationalStep.hs
  kore/src/Kore/Step/Remainder.hs
  kore/src/Kore/Step/RewriteStep.hs
  kore/src/Kore/Step/Rule/Expand.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/Condition.hs
  kore/src/Kore/Step/Simplification/Equals.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Step/Simplification/Iff.hs
  kore/src/Kore/Step/Simplification/Implies.hs
  kore/src/Kore/Step/Simplification/Not.hs
  kore/src/Kore/Step/Simplification/Rule.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/Unification/Error.hs
  kore/src/Kore/Unification/SubstitutionNormalization.hs
  kore/src/Kore/Unification/SubstitutionSimplifier.hs
  kore/src/Kore/Unification/UnifierImpl.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Internal/Pattern.hs
  kore/test/Test/Kore/Internal/Predicate.hs
  kore/test/Test/Kore/Internal/Substitution.hs
  kore/test/Test/Kore/Step/Axiom/Matcher.hs
  kore/test/Test/Kore/Step/EquationalStep.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/Application.hs
  kore/test/Test/Kore/Step/Simplification/Ceil.hs
  kore/test/Test/Kore/Step/Simplification/Condition.hs
  kore/test/Test/Kore/Step/Simplification/Equals.hs
  kore/test/Test/Kore/Step/Simplification/Exists.hs
  kore/test/Test/Kore/Step/Simplification/Floor.hs
  kore/test/Test/Kore/Step/Simplification/Forall.hs
  kore/test/Test/Kore/Step/Simplification/Iff.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  kore/test/Test/Kore/Step/Simplification/Not.hs
  kore/test/Test/Kore/Step/Simplification/Or.hs
  kore/test/Test/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
  kore/test/Test/Kore/Unification/Unifier.hs
  kore/test/Test/Kore/Unification/UnifierT.hs
  kore/test/Test/Kore/Unparser.hs
Labels: automerge

#1436 Use the Simplified monoid
  kore/src/Kore/Attribute/Pattern.hs
  kore/src/Kore/Builtin/AssociativeCommutative.hs
  kore/src/Kore/Internal/Condition.hs
  kore/src/Kore/Internal/Pattern.hs
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Internal/Substitution.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/Simplification/And.hs
  kore/src/Kore/Step/Simplification/AndPredicates.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Step/Simplification/Mu.hs
  kore/src/Kore/Step/Simplification/NoConfusion.hs
  kore/src/Kore/Step/Simplification/Nu.hs
  kore/test/Test/Kore/Step/Simplification/Ceil.hs
Labels: automerge

#1441 Clarify Side conditions design doc after discussion with yi.zhang
  design-decisions/2020-01-02-Side-conditions-for-predicates.md
Labels: automerge

#1409 No branching for functions
  kore/src/Kore/Attribute/Pattern.hs
  kore/src/Kore/Attribute/Pattern/Simplified.hs
  kore/src/Kore/Builtin/Endianness/Endianness.hs
  kore/src/Kore/Builtin/Signedness/Signedness.hs
  kore/src/Kore/Internal/Condition.hs
  kore/src/Kore/Internal/OrCondition.hs
  kore/src/Kore/Internal/OrPattern.hs
  kore/src/Kore/Internal/Pattern.hs
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Internal/SideCondition.hs
  kore/src/Kore/Internal/SideCondition/SideCondition.hs
  kore/src/Kore/Internal/Substitution.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/Remainder.hs
  kore/src/Kore/Step/Simplification/Forall.hs
  kore/src/Kore/Step/Simplification/Not.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Step/Substitution.hs
  kore/test/Test/Kore/Internal/Predicate.hs
  kore/test/Test/Kore/Step/EquationalStep.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Step/Simplification.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/Simplification/Ceil.hs
  kore/test/Test/Kore/Step/Simplification/Equals.hs
  kore/test/Test/Kore/Step/Simplification/Floor.hs
  kore/test/Test/Kore/Step/Simplification/Iff.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  kore/test/Test/Kore/Step/Simplification/IntegrationProperty.hs
  kore/test/Test/Kore/Unification/Unifier.hs
  kore/test/Test/Kore/Unification/UnifierT.hs
  src/main/python/debugFilter.py
  test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
Labels: automerge

#1457 Add link to yq in README.md
  README.md
Labels: automerge

#1452 Remove map constructor for single, opaque element maps
  kore/src/Kore/Domain/Builtin.hs
  kore/src/Kore/Step/Simplification/Builtin.hs
  kore/test/Test/Kore/Step/Simplification/Builtin.hs
Labels: automerge

#1455 Optimize smt
  kore/src/Kore/Internal/MultiOr.hs
  kore/src/Kore/Internal/OrCondition.hs
  kore/src/Kore/Internal/OrPattern.hs
  kore/src/Kore/Step/Axiom/Evaluate.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/Simplification/OrPattern.hs
  kore/test/Test/Kore/Step/Axiom/Evaluate.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/Simplification/OrPattern.hs
  test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
Labels: automerge

#1459 `Kore.Attribute.Symbol.NoEvaluators`
  kore/src/Kore/Attribute/Symbol.hs
  kore/src/Kore/Attribute/Symbol/NoEvaluators.hs
  kore/test/Test/Kore/Attribute/Symbol.hs
  kore/test/Test/Kore/Attribute/Symbol/NoEvaluators.hs
  kore/test/Test/Kore/Internal/Symbol.hs
Labels: automerge

#1468 Stop using side conditions for substitutions
  kore/src/Kore/Builtin/KEqual.hs
  kore/src/Kore/Step/Remainder.hs
  kore/src/Kore/Step/Simplification/And.hs
  kore/src/Kore/Step/Simplification/AndPredicates.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Step/Simplification/Condition.hs
  kore/src/Kore/Step/Simplification/Equals.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Step/Simplification/Iff.hs
  kore/src/Kore/Step/Simplification/Implies.hs
  kore/src/Kore/Step/Simplification/Not.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/Unification/SubstitutionSimplifier.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
  kore/test/Test/Kore/Step/Simplification/Iff.hs
  kore/test/Test/Kore/Step/Simplification/Implies.hs
  kore/test/Test/Kore/Step/Simplification/Not.hs
  kore/test/Test/Kore/Step/Simplification/SubstitutionSimplifier.hs
Labels: automerge

#1478 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1479 refreshVariable tests
  kore/test/Test/Kore.hs
  kore/test/Test/Kore/Variables/Fresh.hs
Labels: automerge

#1485 Update dependency: deps/k_release
  deps/k_release
  test/fresh-vars/1.fresh-vars.out.golden
  test/fresh-vars/fresh-vars.k
Labels: automerge

#1487 docs/hooks.md: add entry for 'STRING.int2string'
  docs/hooks.md
Labels: automerge

#1489 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1488 Remove CharSet
  kore/bench/parser/Main.hs
  kore/src/Kore/Parser/CString.hs
  kore/src/Kore/Parser/CharSet.hs
  kore/src/Kore/Parser/Lexeme.hs
  kore/test/Test/Kore.hs
  kore/test/Test/Kore/Parser/CharSet.hs
  kore/test/Test/Kore/Parser/Lexeme.hs
  kore/test/resources/test-exception-4.kore.golden
  kore/test/resources/test-exception-5.kore.golden
  kore/test/resources/test-exception-6.kore.golden
  kore/test/resources/test-exception-7.kore.golden
Labels: automerge

#1497 Add LIST.size hook
  docs/hooks.md
  kore/src/Kore/Builtin/List.hs
  kore/src/Kore/Builtin/List/List.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Builtin/List.hs
Labels: automerge

#1474 Fix the simplified attribute when refusing to branch
  kore/src/Kore/Attribute/Pattern.hs
  kore/src/Kore/Attribute/Pattern/Simplified.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Internal/Condition.hs
  kore/src/Kore/Internal/Conditional.hs
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Internal/SideCondition.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
  kore/src/Kore/Log/DebugAxiomEvaluation.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Step/Simplification/Pattern.hs
  kore/src/Kore/Step/Simplification/Simplify.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/test/Test/Kore/Step/Axiom/Evaluate.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Strategies/Common.hs
  kore/test/Test/Kore/Unification/Unifier.hs
  kore/test/Test/Kore/Unification/UnifierT.hs
  kore/test/Test/Kore/Unparser.hs
  test/imp/1.merge.out.golden
  test/imp/2.merge.out.golden
  test/imp/sum-save-proofs-spec.k.save-proofs.kore.golden
  test/regression-evm-semantics-39dd1e5/test-add0.sh.out.golden
  test/regression-evm-semantics-39dd1e5/test-branching-invalid.sh.out.golden
  test/regression-evm-semantics-39dd1e5/test-branching-no-invalid.sh.out.golden
  test/regression-evm-semantics-39dd1e5/test-pop1.sh.out.golden
  test/regression-evm-semantics-39dd1e5/test-straight-line-no-invalid.sh.out.golden
  test/regression-evm-semantics-39dd1e5/test-straight-line.sh.out.golden
  test/regression-evm-semantics-39dd1e5/test-sum-to-n.sh.out.golden
  test/regression-evm-semantics-39dd1e5/test-sumTo10.sh.out.golden
  test/regression-wasm-semantics-840390f/test-locals.sh.out.golden
  test/regression-wasm-semantics-840390f/test-loops.sh.out.golden
  test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
  test/regression-wasm-semantics-840390f/test-memory-symbolic-type.sh.out.golden
  test/regression-wasm-semantics-840390f/test-simple-arithmetic.sh.out.golden
  test/save-proofs/test-1-spec.k.save-proofs.kore.golden
  test/simplified/Makefile
  test/simplified/five-spec.k
  test/simplified/five-spec.k.out.golden
  test/simplified/four-spec.k
  test/simplified/four-spec.k.out.golden
  test/simplified/one-spec.k
  test/simplified/one-spec.k.out.golden
  test/simplified/seven-spec.k
  test/simplified/seven-spec.k.out.golden
  test/simplified/simplified.k
  test/simplified/six-spec.k
  test/simplified/six-spec.k.out.golden
  test/simplified/three-spec.k
  test/simplified/three-spec.k.out.golden
  test/simplified/two-spec.k
  test/simplified/two-spec.k.out.golden
Labels: automerge
