Repository runtimeverification/haskell-backend, pull requests merged in 2020-10, with the labels that each got.

#2172 Reset the SMT solver at fixed intervals
  kore/src/Kore/Reachability/Claim.hs
  kore/src/Log.hs
  kore/src/Prof.hs
  kore/src/SMT.hs
  kore/src/SMT/SimpleSMT.hs
Labels: automerge

#2165 Normalize order of terms in \equals
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/Equals.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Prelude/Kore.hs
  kore/test/Test/Kore/Equation/Application.hs
  kore/test/Test/Kore/Reachability/OnePathStrategy.hs
  kore/test/Test/Kore/Step.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Step/Simplification/Condition.hs
  kore/test/Test/Kore/Step/Simplification/Exists.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  kore/test/Test/Kore/Step/Simplification/OrPattern.hs
  test/bmc/fail-2-non-positive-bmc-spec.k.out.golden
  test/bmc/fail-2-positive-bmc-spec.k.out.golden
  test/bmc/fail-3-bmc-spec.k.out.golden
  test/bmc/fail-4-bmc-spec.k.out.golden
  test/imp/2.merge.out.golden
  test/imp/sum-save-proofs-spec.k.out.golden
  test/imp/sum-save-proofs-spec.k.save-proofs.kore.golden
  test/issue-1872/1.test.out.golden
  test/issue-2095/test-issue-2095.sh.out.golden
  test/k-equal/iszero-ge-spec.k.out.golden
  test/k-equal/iszero-gt-spec.k.out.golden
  test/priority/1.merge.out.golden
  test/priority/2.merge.out.golden
  test/remove-destination/test-1-spec.k.out.golden
  test/symbolic-ensures/1.strict.out.golden
Labels: automerge

#2179 Made git ignore hie.yaml
  .gitignore
Labels: automerge, cleanup, meta

#2176 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2170 Move simplifyConjunctionByAssumption to Condition simplifier
  kore/src/Kore/Internal/MultiAnd.hs
  kore/src/Kore/Reachability/Claim.hs
  kore/src/Kore/Step/Simplification/And.hs
  kore/src/Kore/Step/Simplification/Condition.hs
  kore/src/Kore/Step/Simplification/Pattern.hs
  kore/test/Test/Kore/Reachability/Claim.hs
  kore/test/Test/Kore/Reachability/OnePathStrategy.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
  kore/test/Test/Kore/Step/Simplification/Equals.hs
  kore/test/Test/Kore/Step/Simplification/Pattern.hs
Labels: automerge

#2198 final log now falls under initial context
  kore/src/Kore/Equation/Application.hs
Labels: automerge, cleanup

#2203 Update dependency: deps/k_release
  deps/k_release
  test/itp-nth-ancestor/nth1-spec.k
  test/itp-nth-ancestor/nth2-spec.k
Labels: automerge

#2181 Unsatisfiable side condition involving `\forall`: add `translatePredicateForall`
  kore/src/Kore/Step/SMT/Translate.hs
  test/issue-2138/Makefile
  test/issue-2138/issue-2138-spec.k
  test/issue-2138/issue-2138-spec.k.out.golden
  test/issue-2138/test.k
Labels: automerge

#2212 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2209 kore-exec: make --strategy all default; clean-up
  kore/app/exec/Main.hs
  kore/src/Kore/Attribute/Axiom.hs
  kore/src/Kore/Attribute/HeatCool.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/ClaimPattern.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/test/Test/Kore/Attribute/HeatCool.hs
Labels: automerge

#2199 Prove claims in fixed order
  kore/app/share/GlobalMain.hs
  kore/src/Kore/ASTVerifier/DefinitionVerifier.hs
  kore/test/Test/Kore.hs
  kore/test/Test/Kore/Builtin.hs
  kore/test/Test/Kore/Builtin/Definition.hs
Labels: automerge

#2211 Revert change in Simplification.TermLike.ensureSimplifiedResult
  kore/src/Kore/Step/Simplification/TermLike.hs
Labels: automerge

#2213 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2200 Kore.Reachability: decouple result type of applyClaims and applyAxioms
  kore/src/Kore/Reachability/AllPathClaim.hs
  kore/src/Kore/Reachability/Claim.hs
  kore/src/Kore/Reachability/OnePathClaim.hs
  kore/test/Test/Kore/Reachability/MockAllPath.hs
Labels: automerge

#2225 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2224 Retry SMT query once if it fails
  kore/src/Kore/Log/ErrorDecidePredicateUnknown.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/WarnRetrySolverQuery.hs
  kore/src/Kore/Step/SMT/Evaluator.hs
Labels: automerge
