Repository runtimeverification/haskell-backend, pull requests merged in 2020-09, with the labels that each got.

#2096 Reset SMT solver
  kore/app/exec/Main.hs
  kore/app/repl/Main.hs
  kore/bench/exec/Main.hs
  kore/bench/parser/Main.hs
  kore/package.yaml
  kore/src/Kore/Strategies/Goal.hs
  kore/src/SMT.hs
  kore/src/SMT/SimpleSMT.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Builtin/Int.hs
  kore/test/Test/Kore/Builtin/InternalBytes.hs
  kore/test/Test/Kore/Builtin/KEqual.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Builtin/String.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Step/SMT/Helpers.hs
  kore/test/Test/Kore/Step/Simplification.hs
  kore/test/Test/Kore/Step/Simplification/IntegrationProperty.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
  kore/test/Test/Kore/Strategies/Common.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  kore/test/Test/SMT.hs
Labels: automerge

#2117 Revert "Symbolic rules for SET.in (#2073)"
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
Labels: bug

#2098 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2122 Make concatMap symbol function instead of functional
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/Equals.hs
  kore/test/Test/Kore/Unification/Unifier.hs
Labels: automerge

#2112 Stop execution on ErrorBottomTotalFunction (#2088)
  kore/src/Kore/Log/ErrorBottomTotalFunction.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/Simplification/Application.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Step/Simplification/TermLike.hs
Labels: automerge

#2129 ==Int simplification
  kore/test/Test/Kore/Builtin/Int.hs
Labels: automerge

#2133 Update dependency: deps/k_release
  deps/k_release
  test/bmc/fail-3-bmc-spec.k.out.golden
  test/symbolic-ensures/1.strict.out.golden
Labels: automerge

#2086 Make ErrorDecidePredicateUnknown an actual Error
  kore/src/Kore/Log/ErrorBottomTotalFunction.hs
  kore/src/Kore/Log/ErrorDecidePredicateUnknown.hs
  kore/src/Kore/Log/ErrorRewriteLoop.hs
  kore/src/Kore/Log/ErrorRewritesInstantiation.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Step/Rule/Combine.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Step/SMT/Helpers.hs
  kore/test/Test/Kore/Strategies/Goal.hs
Labels: automerge

#2128 Function evaluator: stop at first applicable equation
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
Labels: automerge

#2134 Remove MultiOr's Functor instance
  kore/src/Kore/Builtin/EqTerm.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Internal/Inj.hs
  kore/src/Kore/Internal/MultiAnd.hs
  kore/src/Kore/Internal/MultiOr.hs
  kore/src/Kore/Internal/OrCondition.hs
  kore/src/Kore/Internal/OrPattern.hs
  kore/src/Kore/ModelChecker/Step.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/src/Kore/Step/ClaimPattern.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/Remainder.hs
  kore/src/Kore/Step/Result.hs
  kore/src/Kore/Step/RewriteStep.hs
  kore/src/Kore/Step/Rule/Simplify.hs
  kore/src/Kore/Step/SMT/Evaluator.hs
  kore/src/Kore/Step/Simplification/AndPredicates.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/Application.hs
  kore/src/Kore/Step/Simplification/Builtin.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Step/Simplification/Condition.hs
  kore/src/Kore/Step/Simplification/Defined.hs
  kore/src/Kore/Step/Simplification/DomainValue.hs
  kore/src/Kore/Step/Simplification/Equals.hs
  kore/src/Kore/Step/Simplification/Exists.hs
  kore/src/Kore/Step/Simplification/Floor.hs
  kore/src/Kore/Step/Simplification/Forall.hs
  kore/src/Kore/Step/Simplification/Iff.hs
  kore/src/Kore/Step/Simplification/Implies.hs
  kore/src/Kore/Step/Simplification/In.hs
  kore/src/Kore/Step/Simplification/Inj.hs
  kore/src/Kore/Step/Simplification/InternalBytes.hs
  kore/src/Kore/Step/Simplification/Mu.hs
  kore/src/Kore/Step/Simplification/Not.hs
  kore/src/Kore/Step/Simplification/Nu.hs
  kore/src/Kore/Step/Simplification/Pattern.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Step/Substitution.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/src/Kore/Syntax/Application.hs
  kore/src/Kore/Syntax/DomainValue.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Internal/OrPattern.hs
  kore/test/Test/Kore/Step/Axiom/Registry.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Step/Simplification.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Strategies/Goal.hs
  kore/test/Test/Kore/Unification/Unifier.hs
Labels: automerge

#2148 Do not export constructor of MultiOr
  kore/src/Kore/Internal/MultiOr.hs
  kore/src/Kore/Step/Simplification/Not.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/test/Test/Kore/Builtin/Map.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
Labels: bug

#2141 Create a Kore.Reachability context
  kore/app/exec/Main.hs
  kore/src/Kore/ASTVerifier/SentenceVerifier.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log/DebugClaimState.hs
  kore/src/Kore/Log/DebugProven.hs
  kore/src/Kore/Log/InfoReachability.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/WarnStuckClaimState.hs
  kore/src/Kore/Log/WarnTrivialClaim.hs
  kore/src/Kore/Reachability.hs
  kore/src/Kore/Reachability/AllPathClaim.hs
  kore/src/Kore/Reachability/Claim.hs
  kore/src/Kore/Reachability/ClaimState.hs
  kore/src/Kore/Reachability/OnePathClaim.hs
  kore/src/Kore/Reachability/Prim.hs
  kore/src/Kore/Reachability/Prove.hs
  kore/src/Kore/Reachability/SomeClaim.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Step/AxiomPattern.hs
  kore/src/Kore/Step/ClaimPattern.hs
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Step/Rule/Expand.hs
  kore/src/Kore/Step/Rule/Simplify.hs
  kore/src/Kore/Strategies/ProofState.hs
  kore/src/Kore/Strategies/Rule.hs
  kore/test/Test/Expect.hs
  kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/SentenceVerifier.hs
  kore/test/Test/Kore/Reachability/Claim.hs
  kore/test/Test/Kore/Reachability/MockAllPath.hs
  kore/test/Test/Kore/Reachability/OnePathStrategy.hs
  kore/test/Test/Kore/Reachability/Prove.hs
  kore/test/Test/Kore/Reachability/SomeClaim.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Step/Rule.hs
  kore/test/Test/Kore/Step/Rule/Common.hs
  kore/test/Test/Kore/Step/Rule/Expand.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
  kore/test/Test/Kore/Strategies/AllPath/Verification.hs
  kore/test/Test/Kore/Strategies/Common.hs
  kore/test/Test/Kore/Strategies/OnePath/Verification.hs
Labels: automerge

#2163 test/include.mk: Do not hide stderr
  test/include.mk
Labels: automerge

#2161 Delete unused modules
  kore/src/Generically.hs
  kore/src/Template/Tools.hs
Labels: automerge, cleanup

#2154 mkDefined doesn't preserve "simplified" attribute
  kore/src/Kore/Internal/TermLike.hs
  kore/test/Test/Kore/Internal/TermLike.hs
Labels: automerge

#2164 Disable function evaluation when simplifying Equation's argument predicate
  kore/src/Kore/Equation/Application.hs
  kore/test/Test/Kore/Equation/Application.hs
Labels: automerge

#2167 Filter unsatisfiable patterns from the right-hand side of claims
  kore/src/Kore/Reachability/Claim.hs
  kore/test/Test/Kore/Reachability/Claim.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
Labels: automerge

#2169 Use hasSimplifiedChildren in term simplifier check
  kore/src/Kore/Attribute/Pattern/Simplified.hs
  kore/src/Kore/Internal/MultiAnd.hs
  kore/src/Kore/Internal/OrPattern.hs
  kore/src/Kore/Internal/Pattern.hs
  kore/src/Kore/Step/Simplification/Floor.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/test/Test/Kore/Internal/Pattern.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/IntegrationProperty.hs
Labels: automerge

#2166 Simplification.And.retractLocalFunction: cases for sort inj and builtins
  kore/src/Kore/Step/Simplification/And.hs
  kore/test/Test/Kore/Step/Simplification/And.hs
  test/symbolic-ensures/1.strict.out.golden
Labels: automerge
