Repository runtimeverification/haskell-backend, pull requests merged in 2020-11, with the labels that each got.

#2239 Fix SideCondition normalization error
  kore/src/Kore/Step/Simplification/Pattern.hs
  test/issue-2221/Makefile
  test/issue-2221/spec.kore
  test/issue-2221/test-issue-2221.sh
  test/issue-2221/test-issue-2221.sh.out.golden
  test/issue-2221/vdefinition.kore
Labels: automerge

#2231 Do not ignore `--strategy all`
  kore/src/Kore/Exec.hs
  kore/src/Kore/Internal/MultiOr.hs
  test/imp/imp.k
  test/imp/impossible-branch.imp.out.golden
  test/imp/max-symbolic.imp.out.golden
  test/issue-2010/1.test.out.golden
  test/search/initial.search.out.golden
Labels: automerge

#2230 Rule merger: bug fix and better error messages
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log/ErrorRuleMergeDuplicate.hs
  kore/src/Kore/Log/Registry.hs
Labels: automerge

#2241 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2255 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2260 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2258 Parse signed hex values
  kore/src/Kore/Builtin/String.hs
  kore/test/Test/Kore/Builtin/String.hs
Labels: type: bug

#2261 SMT.Translate.translatePattern: add fallback for translateApplication
  kore/src/Kore/Step/SMT/Translate.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Equation/Application.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Rule/Combine.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Step/SMT/Evaluator.hs
  kore/test/Test/Kore/Step/SMT/Translate.hs
  kore/test/Test/Kore/Step/Simplification/OrPattern.hs
Labels: type: bug

#2267 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2263 Fix bug report: --smt-reset-interval
  kore/app/exec/Main.hs
  kore/src/Options/SMT.hs
Labels: automerge

#2271 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2274 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#2277 Separate SideCondition and SideCondition.Representation
  kore/src/Kore/Internal/Conditional.hs
  kore/src/Kore/Internal/SideCondition.hs
  kore/src/Kore/Internal/SideCondition/SideCondition.hs
  kore/src/Kore/Internal/Variable.hs
Labels: automerge

#2281 LIST.update is \bottom for negative indices
  docs/hooks.md
  kore/src/Kore/Builtin/List.hs
  kore/test/Test/Kore/Builtin/List.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
Labels: automerge

#2288 Fix pull request template formatting
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: cleanup

#2291 Do not freeze kore itself
  .github/workflows/test.yml
  cabal.project.freeze
  scripts/cabal-freeze.sh
Labels: automerge
