Repository runtimeverification/haskell-backend, pull requests merged in 2020-07, with the labels that each got.

#1935 kore: Build executables with -eventlog
  kore/package.yaml
Labels: automerge

#1940 Make `WarnBottomTotalFunction` an error
  kore/src/Kore/Log/ErrorBottomTotalFunction.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/SQLite.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/test/Test/Kore/Log/ErrorBottomTotalFunction.hs
  kore/test/Test/Kore/Log/WarnBottomTotalFunction.hs
Labels: automerge

#1937 Design document for combining priority axioms
  docs/2020-06-22-Rewrite-Rule-Priorities.md
  docs/2020-06-30-Combining-Priority-Axioms.md
Labels: automerge

#1939 Make `WarnDecidePredicateUnknown` an error
  kore/src/Kore/Log/ErrorDecidePredicateUnknown.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Step/SMT/Evaluator.hs
Labels: automerge

#1932 Refactor reachability proof strategies
  kore/src/Kore/Log/DebugProofState.hs
  kore/src/Kore/Log/InfoReachability.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/ProofState.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  test/imp/Makefile
  test/imp/sum-breadth-limit-three-spec.k
  test/imp/sum-breadth-limit-three-spec.k.out.golden
Labels: automerge

#1936 Use entire goal in proof strategy
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge

#1950 Prove infeasible states
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/ProofState.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
  test/issue-1665/Makefile
  test/issue-1665/issue-1665-spec.k
  test/issue-1665/issue-1665-spec.k.out.golden
  test/issue-1665/test.k
Labels: automerge

#1952 kore-repl: do not remove direct children of branchings when using clear command
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
Labels: automerge, bug

#1967 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1966 Kore profiling
  default.nix
  hie-cabal.yaml
  hie-stack.yaml
  kore/app/exec/Main.hs
  kore/app/prof/Main.hs
  kore/app/profiler/Main.hs
  kore/package.yaml
  kore/src/Kore/Builtin/AssociativeCommutative.hs
  kore/src/Kore/Equation/Simplification.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Profiler/Data.hs
  kore/src/Kore/Profiler/Profile.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Step/Axiom/Identifier.hs
  kore/src/Kore/Step/Function/Evaluator.hs
  kore/src/Kore/Step/SMT/Evaluator.hs
  kore/src/Kore/Step/Simplification/Application.hs
  kore/src/Kore/Step/Simplification/Condition.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Simplification/Pattern.hs
  kore/src/Kore/Step/Simplification/Rule.hs
  kore/src/Kore/Step/Simplification/Simplifier.hs
  kore/src/Kore/Step/Simplification/Simplify.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/src/Kore/Step/Strategy.hs
  kore/src/Kore/Step/Transition.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/src/Kore/Unification/UnifierT.hs
  kore/src/Log.hs
  kore/src/Prelude/Kore.hs
  kore/src/Prof.hs
  kore/src/SMT.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Step/Simplification/TermLike.hs
  kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
  nix/sources.json
  shell.nix
  stack.yaml
  stack.yaml.lock
Labels: automerge

#1969 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1970 BugReport: improve help message
  kore/src/Kore/BugReport.hs
Labels: automerge

#1959 Emit a different warning type for each case of stuck proof state
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/WarnStuckProofState.hs
  kore/src/Kore/Strategies/Goal.hs
Labels: automerge

#1972 simplifyEvaluated: Use local mock simplifier
  kore/test/Test/Kore/Step/Simplification/TermLike.hs
Labels: automerge

#1947 TermLike.TermLike: add Defined node to TermLike
  kore/src/Kore/Builtin/External.hs
  kore/src/Kore/Internal/Condition.hs
  kore/src/Kore/Internal/Pattern.hs
  kore/src/Kore/Internal/Substitution.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
  kore/src/Kore/Step/SMT/Translate.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Step/Simplification/Defined.hs
  kore/src/Kore/Step/Simplification/TermLike.hs
  kore/test/Test/ConsistentKore.hs
  kore/test/Test/Kore/Internal/Pattern.hs
  kore/test/Test/Kore/Internal/Substitution.hs
  kore/test/Test/Kore/Internal/TermLike.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
Labels: automerge

#1953 kore-repl: add rules command which lists applied rules between two nodes
  kore/src/Kore/Attribute/Axiom.hs
  kore/src/Kore/Attribute/RuleIndex.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge

#1977 One more change for #1953
  kore/src/Kore/Repl.hs
Labels: automerge

#1979 Prelude.Kore: Export Semigroup and NonEmpty
  kore/src/Prelude/Kore.hs
Labels: automerge

#1980 Missing instance MonadProf for StateT
  kore/src/Prof.hs
Labels: automerge

#1987 Synchronous logging
  kore/app/exec/Main.hs
  kore/src/Kore/BugReport.hs
  kore/src/Kore/Log.hs
Labels: automerge

#1976 kore-repl: debug-equation dynamically
  kore/src/Kore/Log/KoreLogOptions.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge

#1991 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1973 Do not resolve sorts for smtlib symbols
  kore/src/Kore/Step/SMT/AST.hs
  kore/src/Kore/Step/SMT/Representation/Resolve.hs
  kore/src/Kore/Step/SMT/Representation/Symbols.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/SMT/Representation/Builders.hs
  kore/test/Test/Kore/Step/SMT/Representation/Symbols.hs
  kore/test/Test/Kore/Step/SMT/Symbols.hs
  kore/test/Test/Kore/With.hs
Labels: automerge

#1982 Log the depth of execution and proof graphs
  .hlint.yaml
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log/InfoExecDepth.hs
  kore/src/Kore/Log/InfoProofDepth.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Step.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/Verification.hs
Labels: automerge

#1974 Begin to plug the profiling gaps in the \ceil simplifier
  kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/Ceil.hs
  kore/src/Kore/Step/Simplification/Ceil.hs-boot
  kore/src/Kore/Step/Simplification/CeilSimplifier.hs
  kore/src/Kore/Step/Simplification/Equals.hs
  kore/src/Kore/Step/Simplification/Simplify.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/src/Kore/Unification/Procedure.hs
Labels: automerge

#1981 Synthetic attribute instances should not allocate
  kore/src/Kore/Attribute/Synthetic.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
Labels: automerge

#1984 Clean up Kore.Step.Rule.Expand
  kore/src/Kore/Step/Rule/Expand.hs
Labels: automerge

#1983 Allow redirection and piping with aliases
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge

#1997 Bug fix for symbolic narrowing
  kore/CHANGELOG.md
  kore/src/Kore/Internal/Pattern.hs
  kore/src/Kore/Internal/Substitution.hs
  kore/src/Kore/Rewriting/RewritingVariable.hs
  kore/test/Test/Kore/Internal/Pattern.hs
  kore/test/Test/Kore/Internal/Substitution.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
Labels: automerge, bug

#1898 Merge priority rules
  docs/2020-06-30-Combining-Priority-Axioms.md
  kore/src/Kore/ASTVerifier/SentenceVerifier.hs
  kore/src/Kore/Step/AntiLeft.hs
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Step/Rule/Combine.hs
  kore/src/Kore/Step/Rule/Expand.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/src/Kore/Step/Simplification/Rule.hs
  kore/test/Test/Kore/Exec.hs
  kore/test/Test/Kore/Step/AntiLeft.hs
  kore/test/Test/Kore/Step/Rule/Combine.hs
  kore/test/Test/Kore/Step/RulePattern.hs
  test/priority/1.merge
  test/priority/1.merge.out.golden
  test/priority/2.merge
  test/priority/2.merge.out.golden
  test/priority/Makefile
  test/priority/priority.k
Labels: automerge

#2000 No bug report on UserInterrupt
  kore/src/Kore/BugReport.hs
Labels: automerge

#1999 Abbreviate help command
  kore/src/Kore/Repl/Data.hs
Labels: automerge

#1998 Handle Z3 exceptions
  kore/src/SMT.hs
  kore/src/SMT/SimpleSMT.hs
Labels: automerge

#2005 Warn when productivity is low
  kore/app/exec/Main.hs
  kore/app/repl/Main.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/WarnIfLowProductivity.hs
Labels: automerge

#2006 No bug report on ExitSuccess
  kore/src/Kore/BugReport.hs
Labels: automerge

#1995 Update dependency: deps/k_release
  deps/k_release
  test/imp/1.merge.out.golden
  test/imp/2.merge.out.golden
  test/imp/sum-save-proofs-spec.k.save-proofs.kore.golden
  test/overloads/simple-lists/broken-spec.k.out.golden
  test/priority/1.merge.out.golden
  test/priority/2.merge.out.golden
  test/remove-destination/test-1-spec.k.out.golden
  test/save-proofs/test-1-spec.k.out.golden
  test/save-proofs/test-1-spec.k.save-proofs.kore.golden
Labels: automerge

#2003 InfoReachability: Log all interesting proof steps
  kore/src/Kore/Log/InfoReachability.hs
  kore/src/Kore/Strategies/Verification.hs
Labels: bug

#2008 Add SET.inclusion hook
  docs/hooks.md
  kore/src/Kore/Builtin/Set.hs
  kore/src/Kore/Builtin/Set/Set.hs
  kore/test/Test/Kore/Builtin/Definition.hs
  kore/test/Test/Kore/Builtin/Set.hs
Labels: automerge

#2013 mkDefined: Descend into elements of collections
  kore/src/Kore/Internal/TermLike.hs
  kore/test/Test/Kore/Attribute/Pattern/ConstructorLike.hs
  kore/test/Test/Kore/Internal/TermLike.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
Labels: automerge, bug

#2024 Update dependency: deps/k_release
  deps/k_release
  test/kreflection/1.kreflection
  test/kreflection/Makefile
  test/kreflection/kreflection.k
  test/kreflection/test-kreflection.sh
  test/kreflection/test-kreflection.sh.out.golden
Labels: automerge

#2007 Change the representation of reachability claims, part 1
  kore/src/Kore/Internal/Conditional.hs
  kore/src/Kore/Internal/OrPattern.hs
  kore/src/Kore/Internal/Pattern.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Rewriting/RewritingVariable.hs
  kore/src/Kore/Step/ClaimPattern.hs
  kore/src/Kore/Step/Rule.hs
  kore/src/Kore/Step/Rule/Expand.hs
  kore/src/Kore/Step/Rule/Simplify.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/test/Test/Kore/Step/Rule.hs
  kore/test/Test/Kore/Step/Rule/Common.hs
  kore/test/Test/Kore/Step/Rule/Expand.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
Labels: automerge

#2030 default.nix: Add kore attribute
  default.nix
Labels: bug

#2015 checkSubstitutionCoverage: check for constructor-like configuration
  kore/src/Kore/Log/ErrorRewritesInstantiation.hs
  test/imp/disjunction-in-simplification-spec.k
  test/imp/disjunction-in-simplification-spec.k.out.golden
  test/issue-2010/1.test
  test/issue-2010/1.test.out.golden
  test/issue-2010/Makefile
  test/issue-2010/test.k
Labels: automerge

#2031 package.yaml: Enable RTS statistics when compiling without threads
  kore/package.yaml
Labels: automerge, bug

#2033 trackProofDepth: Strict in ProofDepth
  kore/src/Kore/Strategies/Verification.hs
Labels: automerge, bug

#2017 Add context to some error messages
  kore/src/ErrorContext.hs
  kore/src/Kore/Internal/Condition.hs
  kore/src/Kore/Internal/Substitution.hs
  kore/src/Pretty.hs
Labels: automerge, feature
