Repository runtimeverification/haskell-backend, pull requests merged in 2020-05, with the labels that each got.

#1787 Fix sorting bugs around RulePattern
  kore/src/Kore/Internal/Conditional.hs
  kore/src/Kore/Step/Rule/Simplify.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/test/Test/Kore/Step/Rule/Simplify.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
Labels: automerge, bug

#1778 Reject RewriteRule when lhs and rhs are the same
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log/ErrorRewriteLoop.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Step/RulePattern.hs
Labels: automerge

#1788 Remove ToRulePattern, Part 2
  kore/src/Kore/Strategies/Goal.hs
Labels: automerge

#1786 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1797 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1802 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1793 Remove ToRulePattern, part 3
  kore/app/exec/Main.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/Verification.hs
  kore/test/Test/Kore/Strategies/AllPath/Verification.hs
  kore/test/Test/Kore/Strategies/Common.hs
  kore/test/Test/Kore/Strategies/OnePath/Verification.hs
Labels: automerge

#1794 Rename free rule variables at initialization
  kore/src/Branch.hs
  kore/src/Kore/Debug.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Internal/Conditional.hs
  kore/src/Kore/Log/DebugProofState.hs
  kore/src/Kore/Profiler/Data.hs
  kore/src/Kore/Profiler/Profile.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Step/Simplification/Data.hs
  kore/src/Kore/Step/Transition.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Strategies/Rule.hs
  kore/src/Kore/Unification/UnifierT.hs
  kore/src/ListT.hs
  kore/src/Log.hs
  kore/src/SMT.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Strategies/AllPath/Verification.hs
  kore/test/Test/Kore/Strategies/Common.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
  kore/test/Test/Kore/Strategies/OnePath/Verification.hs
Labels: automerge

#1789 Interpretation of function rules
  design-decisions/2020-05-02-function-rules.md
Labels: design

#1822 Handle error entry types as exceptions
  kore/app/exec/Main.hs
  kore/src/Kore/Equation/Application.hs
  kore/src/Kore/Log/DebugAppliedRewriteRules.hs
  kore/src/Kore/Log/DebugEvaluateCondition.hs
  kore/src/Kore/Log/DebugProofState.hs
  kore/src/Kore/Log/DebugSolver.hs
  kore/src/Kore/Log/ErrorException.hs
  kore/src/Kore/Log/ErrorRewriteLoop.hs
  kore/src/Kore/Log/ErrorRewritesInstantiation.hs
  kore/src/Kore/Log/InfoAttemptUnification.hs
  kore/src/Kore/Log/InfoReachability.hs
  kore/src/Kore/Log/WarnBottomTotalFunction.hs
  kore/src/Kore/Log/WarnDecidePredicateUnknown.hs
  kore/src/Kore/Log/WarnFunctionWithoutEvaluators.hs
  kore/src/Kore/Log/WarnSymbolSMTRepresentation.hs
  kore/src/Log.hs
  kore/src/Log/Entry.hs
Labels: automerge

#1820 FreeVariables: Do not export constructor
  kore/src/Kore/ASTVerifier/SentenceVerifier.hs
  kore/src/Kore/Attribute/Axiom/Concrete.hs
  kore/src/Kore/Attribute/Axiom/Symbolic.hs
  kore/src/Kore/Attribute/Pattern/FreeVariables.hs
  kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
  kore/src/Kore/Equation/Application.hs
  kore/src/Kore/Equation/Equation.hs
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Internal/Substitution.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Internal/TermLike/Renaming.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
  kore/src/Kore/Rewriting/RewritingVariable.hs
  kore/src/Kore/Rewriting/UnifyingRule.hs
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/Rule/Expand.hs
  kore/src/Kore/Step/RulePattern.hs
  kore/src/Kore/Step/SMT/Evaluator.hs
  kore/src/Kore/Step/Step.hs
  kore/src/Kore/Strategies/Goal.hs
  kore/src/Kore/Substitute.hs
  kore/src/Kore/Syntax/Sentence.hs
  kore/src/Kore/Unification/SubstitutionNormalization.hs
  kore/test/Test/Kore/Internal/Predicate.hs
  kore/test/Test/Kore/Internal/TermLike.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
  kore/test/Test/Kore/Step/RulePattern.hs
  scripts/check.sh
  scripts/run-on-haskell.include.sh
  scripts/stylish.sh
Labels: automerge

#1819 include.mk: compatibility with Windows WSL2
  include.mk
Labels: automerge

#1823 Makefile: Build coverage report with --fast
  Makefile
Labels: automerge

#1810 Use side conditions when rewriting
  kore/src/Kore/Step/RewriteStep.hs
  kore/src/Kore/Step/Step.hs
  kore/test/Test/Kore/Step/RewriteStep.hs
Labels: automerge

#1792 Remove Kore.Internal.SideCondition.andCondition
  kore/src/Kore/Internal/SideCondition.hs
  kore/src/Kore/Step/Simplification/Pattern.hs
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/src/Kore/Unification/Procedure.hs
  kore/test/Test/Kore/Strategies/OnePath/Step.hs
Labels: automerge

#1785 Revert #1784
  kore/CHANGELOG.md
  kore/src/Kore/Builtin/Bool.hs
  kore/src/Kore/Builtin/KEqual.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Builtin/KEqual.hs
  test/not-kequal/Makefile
  test/not-kequal/a.test
  test/not-kequal/a.test.out.golden
  test/not-kequal/test.k
Labels: automerge

#1831 \in simplifier should evaluate \ceil of \and
  kore/src/Kore/Step/Simplification/In.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
Labels: bug

#1837 RewritingVariable: Use default instance of FreshVariable
  kore/src/Kore/Rewriting/RewritingVariable.hs
Labels: automerge

#1836 Prelude.Kore: Export Witherable
  kore/src/Prelude/Kore.hs
Labels: automerge

#1835 Prelude.Kore: Export Category
  kore/src/Prelude/Kore.hs
Labels: automerge

#1796 Overloaded variables
  docs/2019-08-27-Unification-modulo-overloaded-constructors.md
  kore/Makefile
  kore/src/Kore/Builtin.hs
  kore/src/Kore/IndexedModule/OverloadGraph.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Step/Axiom/Matcher.hs
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/src/Kore/Step/Simplification/OverloadSimplifier.hs
  kore/src/Kore/Step/Simplification/Overloading.hs
  kore/src/Kore/Variables/Fresh.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/Overloading.hs
  test/overloads/strict-lists/1.simple-exps
  test/overloads/strict-lists/1.simple-exps.out.golden
  test/overloads/strict-lists/Makefile
  test/overloads/strict-lists/simple-exps.k
Labels: automerge

#1838 Remove Test.Kore.Step.Simplifier
  kore/test/Test/Kore/Step/Simplifier.hs
Labels: automerge

#1834 Add class Injection
  kore/src/Injection.hs
  kore/src/Kore/Step/Simplification/OverloadSimplifier.hs
  kore/src/Kore/Step/Simplification/Overloading.hs
  kore/src/Prelude/Kore.hs
Labels: automerge

#1842 Add new log entry type: DebugSubstitutionSimplifier
  kore/src/Kore/Internal/TermLike/TermLike.hs
  kore/src/Kore/Log/DebugSubstitutionSimplifier.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Log/SQLite.hs
  kore/src/Kore/Unification/SubstitutionSimplifier.hs
Labels: automerge

#1844 Update dependency: deps/k_release
  Jenkinsfile
  deps/k_release
  include.mk
Labels: automerge

#1839 Add function bindVariables
  kore/src/Kore/Attribute/Pattern/FreeVariables.hs
  kore/src/Kore/Step/RulePattern.hs
Labels: automerge

#1846 Add SideCondition argument to simplifyAnds
  kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
  kore/test/Test/Kore/Unification/Unifier.hs
Labels: automerge

#1849 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1852 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#1848 Added documentation for merging rules
  docs/2020-05-22-Merging-Rules.md
  docs/proofs/MergingRules.v
Labels: automerge

#1855 Update dependency: deps/k_release
  deps/k_release
  test/bmc/fail-3-bmc-spec.k.out.golden
  test/fresh-vars/1.fresh-vars.out.golden
  test/imp/sum-save-proofs-spec.k.out.golden
Labels: automerge
