Repository runtimeverification/haskell-backend, pull requests merged in 2021-01, with the labels that each got.

#2340 Minor fix: Debug/Diff Map instances
  kore/src/Debug.hs
Labels: automerge

#2317 Update dependency: deps/k_release
  deps/k_release
  test/kprove/sum-spec.k
Labels: automerge, blocked

#2333 Unify Equation arguments at initialization
  kore/kore.cabal
  kore/src/Kore/Equation/Simplification.hs
  kore/test/Test/Kore/Equation/Application.hs
  kore/test/Test/Kore/Equation/Common.hs
  kore/test/Test/Kore/Equation/Simplification.hs
  kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
  kore/test/Test/Kore/Step/Function/Integration.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/Integration.hs
  nix/kore.nix.d/kore.nix
Labels: automerge

#2335 kore-repl: represent Remaining states correctly
  kore/src/Kore/Reachability/ClaimState.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
  kore/test/Test/Kore/Repl/Graph.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
Labels: automerge

#2346 unifyKequalsEq should apply for both \and and \equals
  kore/src/Kore/Step/Simplification/AndTerms.hs
  kore/test/Test/Kore/Step/MockSymbols.hs
  kore/test/Test/Kore/Step/Simplification/AndTerms.hs
Labels: automerge

#2350 entr.sh: Run hpack when important files change
  .github/workflows/update.yml
  README.md
  entr.sh
  hooks.sh
  scripts/check.sh
  scripts/ci.sh
  scripts/lint.sh
  scripts/run-on-haskell.include.sh
  scripts/stylish.sh
  src/main/python/lint.py
Labels: automerge

#2357 Update dependency: deps/k_release
  deps/k_release
  test/imp/run-stepf-repl-script-spec.k.out.golden
  test/issue-2010/test.k
  test/issue-2205/test.k
Labels: automerge

#2372 Remove Defined markers in simplifyConjunctionByAssumption
  kore/src/Kore/Step/Simplification/Condition.hs
  kore/test/Test/Kore/Step/Simplification/Condition.hs
Labels: type: bug

#2369 kore-parser: Parse and validate multiple pattern files
  kore/app/parser/Main.hs
  kore/app/share/GlobalMain.hs
  kore/src/Kore/Options.hs
Labels: automerge
