Repository runtimeverification/haskell-backend, pull requests merged in 2022-12, with the labels that each got.

#3391 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#3401 pin CI to ubuntu-20.04
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update.yml
Labels: automerge

#3394 Make make tail recursive
  kore/src/Kore/Internal/MultiOr.hs
Labels: automerge, cleanup

#3398 Transfer not simplified claims to applyClaim
  kore/src/Kore/Exec.hs
  kore/src/Kore/Reachability/Prove.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/State.hs
  kore/test/Test/Kore/Reachability/Prove.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
Labels: automerge

#3404 Remove `UnifierT` from `NotSimplifier`
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Simplify/And.hs
  kore/src/Kore/Simplify/AndTerms.hs
  kore/src/Kore/Simplify/Equals.hs
  kore/src/Kore/Unification/SubstitutionSimplifier.hs
  kore/src/Kore/Unification/UnifierT.hs
  kore/test/Test/Kore/Unification/Unifier.hs
Labels: automerge

#3395 Remove keys faster
  kore/src/Kore/Builtin/AssociativeCommutative.hs
  kore/test/Test/Kore/Builtin/Set.hs
Labels: automerge, performance

#3406 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#3413 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#3419 Remove nested `MaybeT`
  kore/src/Kore/Rewrite/Function/Evaluator.hs
Labels: automerge

#3418 Remove nested `ReaderT`
  kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
  kore/src/Kore/Simplify/Ceil.hs
Labels: automerge
