Repository runtimeverification/haskell-backend, pull requests merged in 2022-11, with the labels that each got.

#3348 .github/update: make sure after formatting, CI still runs
  .github/workflows/update.yml
Labels: automerge

#3354 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#3352 Document performance test automations, small fix
  .github/workflows/kevm-performance-test.yaml
  docs/2022-11-02-perf-test-automation.md
Labels: automerge

#3355 Change severity of WarnUnsimplifiedPredicate/Condition
  kore/src/Kore/Log/WarnUnsimplified.hs
Labels: automerge

#3336 Monomorphization of Simplifier, leg #1
  kore/src/Kore/Reachability/Prove.hs
  kore/src/Kore/Rewrite/RewriteStep.hs
  kore/src/Kore/Rewrite/Step.hs
  kore/src/Kore/Simplify/Application.hs
Labels: automerge

#3360 .github/: switch to new cachix system
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update.yml
Labels: automerge

#3359 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#3240 Remove TermLike transformations in EvaluationStrategy
  kore/src/Kore/Rewrite/Axiom/EvaluationStrategy.hs
Labels: automerge

#3363 Revert "Add IO hooks"
  docs/hooks.md
  kore/kore.cabal
  kore/src/Kore/Builtin/IO.hs
  nix/kore-ghc8107.nix.d/kore.nix
  nix/kore-ghc923.nix.d/kore.nix
  test/io-hooks/Makefile
  test/io-hooks/a.test
  test/io-hooks/a.test.out.golden
  test/io-hooks/input
  test/io-hooks/test.k
Labels: automerge

#3361 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#3367 Minor cleanups in Kore.Unification.NewUnifier
  kore/src/Kore/Equation/Application.hs
  kore/src/Kore/Internal/MultiExists.hs
  kore/src/Kore/Internal/Substitution.hs
  kore/src/Kore/ModelChecker/Simplification.hs
  kore/src/Kore/Rewrite/Axiom/Matcher.hs
  kore/src/Kore/Rewrite/ClaimPattern.hs
  kore/src/Kore/Rewrite/Implication.hs
  kore/src/Kore/Rewrite/RewritingVariable.hs
  kore/src/Kore/Rewrite/Rule/Expand.hs
  kore/src/Kore/Rewrite/RulePattern.hs
  kore/src/Kore/Syntax/Variable.hs
  kore/src/Kore/Unification/NewUnifier.hs
  kore/src/Kore/Variables/Fresh.hs
  kore/test/Test/Kore/Internal/MultiExists.hs
Labels: cleanup

#3338 Df/caching termlike hashes
  .stylish-haskell.yaml
  kore/src/Kore/Builtin/AssociativeCommutative.hs
  kore/src/Kore/Builtin/Int/Int.hs
  kore/src/Kore/Builtin/String/String.hs
  kore/src/Kore/Internal/Conditional.hs
  kore/src/Kore/Internal/Substitution.hs
  kore/src/Kore/Internal/TermLike.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
  kore/test/Test/Kore/Builtin.hs
  kore/test/Test/Kore/Builtin/Int.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Builtin/String.hs
  kore/test/Test/Kore/Rewrite/Axiom/Matcher.hs
  kore/test/Test/Kore/Rewrite/MockSymbols.hs
  kore/test/Test/Kore/Simplify.hs
  scripts/fourmolu.sh
  test/regression-c/test-smoke100.sh.out.golden
Labels: automerge, performance

#3370 Remove some redundant instance constraints
  kore/src/Kore/Internal/Predicate.hs
  kore/src/Kore/Internal/TermLike/TermLike.hs
Labels: automerge

#3368 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#3382 Use source location in rewrite trace
  kore/src/Kore/Log/DebugRewriteTrace.hs
  kore/src/Kore/Reachability/Prove.hs
Labels: automerge

#3389 Print build logs when building Nix flakes
  .github/workflows/test.yml
Labels: automerge
