Repository runtimeverification/haskell-backend, pull requests merged in 2023-01, with the labels that each got.

#3392 Try using hoistLogicT
  kore/src/Logic.hs
Labels: automerge, performance, cleanup

#3427 Remove `Kore.Variables.Target`
  kore/kore.cabal
  kore/src/Kore/Internal/OrPattern.hs
  kore/src/Kore/Rewrite/Step.hs
  kore/src/Kore/Variables/Target.hs
  kore/test/Test/Kore.hs
  kore/test/Test/Kore/Internal/Substitution.hs
  kore/test/Test/Kore/Variables/Target.hs
  nix/kore-ghc8107.nix.d/kore.nix
  nix/kore-ghc923.nix.d/kore.nix
Labels: automerge

#3358 Flatten LogicT in constructConfiguration
  kore/src/Kore/Rewrite/RewriteStep.hs
Labels: automerge, Serokell

#3387 Make NotSimplifier a class
  kore/src/Kore/Builtin/Builtin.hs
  kore/src/Kore/Builtin/EqTerm.hs
  kore/src/Kore/Builtin/Map.hs
  kore/src/Kore/Simplify/And.hs
  kore/src/Kore/Simplify/AndTerms.hs
  kore/src/Kore/Simplify/Equals.hs
  kore/src/Kore/Simplify/Iff.hs
  kore/src/Kore/Simplify/Implies.hs
  kore/src/Kore/Simplify/In.hs
  kore/src/Kore/Simplify/Not.hs
  kore/src/Kore/Simplify/NotSimplifier.hs
  kore/src/Kore/Simplify/TermLike.hs
  kore/src/Kore/Unification/SubstitutionSimplifier.hs
  kore/src/Kore/Unification/UnifierT.hs
  kore/test/Test/Kore/Builtin/Bool.hs
  kore/test/Test/Kore/Builtin/Builtin.hs
  kore/test/Test/Kore/Builtin/Endianness.hs
  kore/test/Test/Kore/Builtin/KEqual.hs
  kore/test/Test/Kore/Builtin/Set.hs
  kore/test/Test/Kore/Builtin/Signedness.hs
  kore/test/Test/Kore/Simplify/And.hs
  kore/test/Test/Kore/Simplify/AndTerms.hs
  kore/test/Test/Kore/Simplify/SubstitutionSimplifier.hs
  kore/test/Test/Kore/Unification/Unifier.hs
  kore/test/Test/Kore/Unification/UnifierT.hs
Labels: automerge, cleanup

#3425 Add --allow-vacuous
  kore/app/exec/Main.hs
  kore/app/repl/Main.hs
  kore/app/share/GlobalMain.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log/WarnStuckClaimState.hs
  kore/src/Kore/Reachability/Claim.hs
  kore/src/Kore/Reachability/Prove.hs
  kore/src/Kore/Repl.hs
  kore/test/Test/Kore/Reachability/MockAllPath.hs
  kore/test/Test/Kore/Reachability/OnePathStrategy.hs
  kore/test/Test/Kore/Reachability/Prove.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  test/assume/Makefile
  test/bottom-lhs/Makefile
Labels: automerge

#3433 Add unparsed versions of commands for kore-repl
  kore/app/repl/Main.hs
  kore/kore.cabal
  kore/src/Kore/Exec.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
  nix/kore-ghc8107.nix.d/kore.nix
  nix/kore-ghc923.nix.d/kore.nix
Labels: automerge

#3438 Revert "Add --allow-vacuous (#3425)"
  kore/app/exec/Main.hs
  kore/app/repl/Main.hs
  kore/app/share/GlobalMain.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log/WarnStuckClaimState.hs
  kore/src/Kore/Reachability/Claim.hs
  kore/src/Kore/Reachability/Prove.hs
  kore/src/Kore/Repl.hs
  kore/test/Test/Kore/Reachability/MockAllPath.hs
  kore/test/Test/Kore/Reachability/OnePathStrategy.hs
  kore/test/Test/Kore/Reachability/Prove.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  test/assume/Makefile
  test/bottom-lhs/Makefile
Labels: bug, automerge

#3441 Removing forced nix env setup in workflow
  .github/workflows/kevm-performance-test.yaml
  .github/workflows/profiling.yaml
Labels: automerge

#3443 Add --allow-vacuous, fixed
  kore/app/exec/Main.hs
  kore/app/repl/Main.hs
  kore/app/share/GlobalMain.hs
  kore/src/Kore/Exec.hs
  kore/src/Kore/Log/WarnStuckClaimState.hs
  kore/src/Kore/Reachability/Claim.hs
  kore/src/Kore/Reachability/Prove.hs
  kore/src/Kore/Repl.hs
  kore/test/Test/Kore/Reachability/MockAllPath.hs
  kore/test/Test/Kore/Reachability/OnePathStrategy.hs
  kore/test/Test/Kore/Reachability/Prove.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  test/assume/Makefile
  test/bottom-lhs/Makefile
Labels: automerge

#3446 Add time printing command/option for steps in repl
  kore/app/repl/Main.hs
  kore/kore.cabal
  kore/src/Kore/Exec.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
  nix/kore-ghc8107.nix.d/kore.nix
  nix/kore-ghc923.nix.d/kore.nix
Labels: automerge

#3448 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#3451 Add equational rule label in debug output (#3428)
  kore/src/Kore/Equation/DebugEquation.hs
Labels: automerge

#3457 Fix strictness bug in definedness check
  kore/src/Kore/Internal/SideCondition.hs
Labels: automerge

#3452 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#3456 Fix output of debug rewrite rules (#3428)
  kore/src/Kore/Log/DebugAppliedRewriteRules.hs
  kore/src/Kore/Log/DebugAttemptedRewriteRules.hs
  kore/src/Kore/Log/KoreLogOptions.hs
  kore/src/Kore/Log/Registry.hs
  kore/src/Kore/Rewrite/RewriteStep.hs
  kore/src/Kore/Rewrite/Step.hs
Labels: automerge

#3471 Moving average timeouts
  docs/2022-07-18-JSON-RPC-Server-API.md
  kore/app/exec/Main.hs
  kore/app/repl/Main.hs
  kore/app/share/GlobalMain.hs
  kore/kore.cabal
  kore/src/Kore/Exec.hs
  kore/src/Kore/Exec/GraphTraversal.hs
  kore/src/Kore/JsonRpc.hs
  kore/src/Kore/Log/WarnStepTimeout.hs
  kore/src/Kore/Reachability/Prove.hs
  kore/src/Kore/Repl.hs
  kore/src/Kore/Repl/Data.hs
  kore/src/Kore/Repl/Interpreter.hs
  kore/src/Kore/Repl/Parser.hs
  kore/src/Kore/Repl/State.hs
  kore/src/Kore/Rewrite/Timeout.hs
  kore/test/Test/Kore/Exec.hs
  kore/test/Test/Kore/Reachability/Prove.hs
  kore/test/Test/Kore/Repl/Interpreter.hs
  kore/test/Test/Kore/Repl/Parser.hs
  nix/kore-ghc8107.nix.d/kore.nix
  nix/kore-ghc923.nix.d/kore.nix
Labels: automerge
